import type { CourseRichContent } from "./types";

/**
 * Salesforce Consultant — rich content overlay.
 *
 * Path 4 of the eight in the Salesforce Career Guide 2026. The guide states
 * plainly that this is a progression role, not an entry role, and this
 * course is scoped and gated accordingly — it assumes existing
 * administrator, analyst or implementation experience.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceConsultantTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Consultant sits between business requirements and technical implementation: solution design, configuration, stakeholder management, testing, change management, and enough integration literacy to scope an engagement realistically. Our Salesforce Career Guide 2026 is explicit that this is a progression role rather than an entry one, and this course is scoped for that — it assumes you already administer, analyse or implement on the platform. Three months, aligned to the Sales Cloud and Service Cloud Consultant credentials, built around delivering an engagement end to end rather than learning the platform from scratch.",

  whyLearn: {
    heading: "Why Move Into Salesforce Consulting",
    paragraphs: [
      "Consulting is where the Salesforce ecosystem's compensation genuinely steps up, and the reason is that the job is not configuration. A consultant is accountable for a client outcome: scoping realistically, designing a solution that survives contact with the client's actual processes, managing the stakeholders who disagree about it, and landing the change with people who did not ask for it. The platform skill is assumed; the judgement is the product.",
      "Pune has an unusually deep consulting market — the services majors run large Salesforce practices here and the Salesforce-native partners concentrate their delivery teams in the city. Both hire consultants continuously, and both pay a premium for people who can be put in front of a client. Implementation breadth matters more than years served: someone who has delivered five different client orgs typically moves faster than someone who has maintained one for the same period.",
      "The honest framing, and the one our career guide takes: you cannot start here. A consultant who has never administered an org gives estimates that are wrong and designs that cannot be built, and clients notice quickly. This course assumes two years or so of platform experience and teaches the delivery craft on top of it. If that is not you yet, the Administrator or Business Analyst path is the right starting point and this remains available afterwards.",
    ],
    keyPoints: [
      "A progression role, not an entry role — the course is gated accordingly",
      "Aligned to the Sales Cloud and Service Cloud Consultant credentials",
      "Built around delivering an engagement, not learning the platform",
      "Implementation breadth matters more than years served",
      "Client-facing skill treated as a taught craft, not an assumed trait",
      "Indicative 3–5 year band ₹10–20 LPA, higher at Salesforce-native partners",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "Salesforce administrators with roughly two years of experience wanting client-facing work",
      "Salesforce business analysts moving from specification into solution ownership",
      "Functional consultants from other platforms moving into the Salesforce ecosystem",
      "Implementation team members being moved toward client-facing delivery",
      "MBAs with existing platform experience targeting consulting partners",
    ],
    notForYou: [
      "Freshers and career switchers with no Salesforce experience — start with Administrator or Business Analyst; our career guide is explicit that consulting is a progression role",
      "Anyone looking to learn the platform itself; this course assumes it",
      "Candidates who want to stay behind a keyboard, since a consultant is in front of a client most days",
      "Developers wanting technical depth — the Architect path fits that ambition better",
    ],
  },

  curriculum: [
    {
      title: "The Consultant's Remit & Engagement Models",
      weekRange: "Week 1",
      description:
        "What a consultant is accountable for that an administrator is not. Engagement shapes — fixed-scope implementation, time and materials, managed service, staff augmentation — and how each changes what you can promise. Discovery, statements of work, and the commercial context a delivery sits inside.\n\nThe module sets the standard the rest of the course holds you to: every design decision must be defensible to a client who is paying for it.",
      topics: [
        "What a consultant owns beyond configuration",
        "Engagement models and what each permits",
        "Discovery structure and outputs",
        "Statements of work and scope boundaries",
        "Commercial context of a delivery",
        "Working within a partner delivery methodology",
        "Client expectations and how they are set",
        "Escalation and when to raise a risk",
      ],
    },
    {
      title: "Discovery, Scoping & Estimation",
      weekRange: "Week 2",
      description:
        "The phase that decides whether a project succeeds, conducted before anyone has agreed anything. Running discovery workshops with client stakeholders, current-state assessment, and turning findings into a scope that can be delivered in the time and budget available.\n\nEstimation is taught as a discipline with its failure modes named: optimism on integration, silence on data migration, and the standard omission of testing and change management. You estimate a real scenario and then defend it.",
      topics: [
        "Running a discovery workshop",
        "Current-state assessment",
        "Turning findings into a deliverable scope",
        "Estimation techniques and ranges",
        "Estimating integration and migration honestly",
        "Assumptions, dependencies and exclusions",
        "Risk identification and mitigation",
        "Defending an estimate under pressure",
      ],
    },
    {
      title: "Sales Cloud Implementation",
      weekRange: "Weeks 3–4",
      description:
        "Implementing the lead-to-cash process rather than configuring its features. Lead capture, qualification, assignment and conversion; opportunity stages designed around how the client's sales team actually works; products, price books and quoting; forecasting; territory management.\n\nThe recurring judgement is fitting the platform to the business without letting the business recreate its worst existing habits in a new system.",
      topics: [
        "Lead capture, assignment and conversion design",
        "Opportunity stages and sales process design",
        "Products, price books and quoting",
        "Forecasting and forecast categories",
        "Territory management",
        "Campaign influence and attribution",
        "Sales productivity features",
        "Fitting the platform to an actual sales process",
      ],
    },
    {
      title: "Service Cloud Implementation",
      weekRange: "Weeks 4–5",
      description:
        "Case management as a designed system. Channels — email, web, phone, chat — case assignment, escalation and queues; entitlements, milestones and service contracts; knowledge management and deflection; omni-channel routing and capacity models.\n\nService implementations fail most often on routing design and on knowledge nobody maintains, so both get more time than their feature complexity would suggest.",
      topics: [
        "Case channels and capture design",
        "Assignment rules, queues and escalation",
        "Entitlements, milestones and service contracts",
        "Knowledge management and article lifecycle",
        "Case deflection and self-service",
        "Omni-channel routing and capacity",
        "Service console design",
        "CSAT and service reporting",
      ],
    },
    {
      title: "Data Migration & Integration Scoping",
      weekRange: "Week 6",
      description:
        "The two areas that most often blow an engagement's timeline. Migration strategy — source analysis, mapping, cleansing, sequencing, reconciliation and the cutover rehearsal that is always cut and always needed.\n\nIntegration is scoped rather than built: identifying the systems, choosing patterns, understanding volumes and latency, deciding between point-to-point and middleware, and being able to tell a client what an integration will actually cost before agreeing to it.",
      topics: [
        "Migration strategy and sequencing",
        "Source analysis, mapping and cleansing",
        "Reconciliation and cutover rehearsal",
        "Integration patterns and when each fits",
        "Volume, latency and API limit implications",
        "Point-to-point versus middleware",
        "Scoping an integration credibly",
        "Third-party and AppExchange evaluation",
      ],
    },
    {
      title: "Solution Design & Governance",
      weekRange: "Week 7",
      description:
        "Designing something that will still work in two years. Declarative-first decision making with a clear threshold for when code is warranted; multi-org and single-org considerations; and technical debt as something a consultant actively prevents rather than inherits.\n\nGovernance covers design authority, documentation standards, environment strategy and release management — the structures that keep a client org from degrading after the consultants leave.",
      topics: [
        "Declarative-first, and the threshold for code",
        "Designing for maintainability",
        "Single-org versus multi-org considerations",
        "Preventing technical debt in a design",
        "Design authority and review",
        "Environment and release strategy",
        "Documentation standards for handover",
        "Designing for the administrator who inherits it",
      ],
    },
    {
      title: "Change Management, UAT & Go-Live",
      weekRange: "Week 8",
      description:
        "Landing the change with people who did not ask for it, which is where technically successful Salesforce projects most often fail. Stakeholder communication, training design for different user groups, and adoption measurement that is honest about whether anyone is using the system.\n\nUAT coordination, defect triage against scope, go-live readiness criteria, cutover planning and hypercare. The module ends on the post-go-live review most engagements skip.",
      topics: [
        "Change management and communication planning",
        "Training design for different user groups",
        "Adoption measurement and honest reporting",
        "UAT coordination and sign-off",
        "Defect triage against agreed scope",
        "Go-live readiness criteria",
        "Cutover planning and rollback",
        "Hypercare and transition to support",
        "Post-implementation review",
      ],
    },
    {
      title: "Client Communication & Difficult Conversations",
      weekRange: "Week 9",
      description:
        "The skill that separates consultants who are asked back from consultants who are competent. Running a steering meeting, presenting a design to people who will not read the document, saying no to a scope change without damaging the relationship, and delivering bad news early rather than hoping.\n\nTaught through role-play with deliberately difficult scenarios — a slipping timeline, a stakeholder who changed their mind, a client blaming the platform for a process problem.",
      topics: [
        "Running a steering meeting",
        "Presenting a design to a non-technical audience",
        "Saying no to scope change constructively",
        "Delivering bad news early",
        "Managing a stakeholder who has changed position",
        "Handling blame directed at the platform",
        "Written communication that holds up later",
        "Building a relationship that survives a difficult project",
      ],
    },
    {
      title: "Certification, Engagement Simulation & Positioning",
      weekRange: "Week 10 + placement prep",
      description:
        "A full engagement simulation — discovery, scope, estimate, design, build plan, UAT approach and a client presentation — assessed the way a delivery lead would assess it. That artefact is what a consulting partner interview actually explores.\n\nAlongside it, preparation for the Sales Cloud and Service Cloud Consultant credentials, and positioning: repositioning an administrator or analyst CV for consulting, and answering the interview question about an engagement you owned.",
      topics: [
        "End-to-end engagement simulation",
        "Client presentation and defence",
        "Sales Cloud Consultant exam preparation",
        "Service Cloud Consultant exam preparation",
        "Scenario question technique and pacing",
        "Repositioning an administrator or analyst CV",
        "Answering questions about an engagement you owned",
        "Mock interview — design and estimation scenarios",
        "Mock interview — client-handling scenarios",
      ],
    },
    {
      title: "AI, Agentforce & Advising Clients About It",
      weekRange: "Final Week",
      description:
        "What a consultant needs to say when a client asks for AI, which in 2026 they will. Agentforce, Data Cloud and Einstein at the level of scoping an engagement: what they need in place first, what they realistically deliver, and what they cost.\n\nOur career guide's caveat becomes a consulting tool here — AI sits on top of strong CRM, data and platform foundations, so the most valuable advice a consultant often gives is that the client's data quality has to be fixed before any agent will be useful. Advising against a purchase is sometimes the engagement.",
      topics: [
        "Agentforce, Data Cloud and Einstein at scoping level",
        "Prerequisites a client must have in place first",
        "What AI features realistically deliver",
        "Cost and licensing implications",
        "Data quality as the blocking dependency",
        "Advising against a premature AI purchase",
        "AI governance and risk questions clients should ask",
        "Scoping an AI-enabled engagement",
        "Using AI assistants in your own delivery work",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-consultant-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Ten-stage Salesforce Consultant progression path taught at Archer Infotech Pune, for people who already have platform experience: the consultant remit and engagement models; discovery, scoping and estimation; Sales Cloud implementation; Service Cloud implementation; data migration and integration scoping; solution design and governance; change management, user acceptance testing and go-live; client communication and difficult conversations; certification with an engagement simulation; and advising clients on AI and Agentforce.",
    caption:
      "A progression track, not an entry one. The order assumes you already administer or analyse on the platform — each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-consultant-syllabus-v1.pdf",
    title: "Salesforce Consultant Syllabus — Complete Module List",
    slug: "salesforce-consultant-syllabus",
    blurb:
      "All eleven modules as a PDF — the consultant remit and engagement models, discovery and estimation, Sales Cloud and Service Cloud implementation, migration and integration scoping, solution design and governance, change management and go-live, client communication, the engagement simulation with consultant certification preparation, and advising clients on AI. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All eleven modules in teaching order, each with its schedule, description and full topic list.",
          "The prerequisite stated plainly at the front — this is a progression track that assumes roughly two years of platform experience, in line with our Salesforce Career Guide 2026.",
          "Estimation and scoping given a full module with the failure modes named: optimism on integration, silence on migration, and the standard omission of testing and change management.",
          "Client communication treated as a taught craft — steering meetings, presenting to non-technical audiences, refusing scope change and delivering bad news early.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Consultant at a services major or Salesforce-native partner.",
          "Salesforce Functional Consultant across Sales and Service Cloud.",
          "Salesforce Implementation Lead.",
          "The delivery grounding beneath the Technical Architect path.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Full Engagement Simulation",
      description:
        "Take a client brief through the whole delivery arc: discovery workshop, current-state assessment, scope with explicit assumptions and exclusions, a defensible estimate, a solution design, a migration and integration approach, a UAT plan, a change and training plan, and a client presentation you deliver and defend. Assessed the way a delivery lead assesses a junior consultant's first engagement.",
      technologies: [
        "Discovery and scoping",
        "Estimation with assumptions",
        "Sales and Service Cloud design",
        "Migration and integration approach",
        "UAT and change planning",
        "Client presentation",
      ],
    },
    {
      title: "Rescue Assessment of a Degraded Org",
      description:
        "Given a deliberately mismanaged org — duplicated automation, profile sprawl, unmaintained knowledge, reports nobody trusts — produce the assessment a client would pay for: what is wrong, what it costs them, what to fix in what order, and what it will take. The engagement type consulting partners are most often called in for.",
      technologies: [
        "Org assessment and health check",
        "Technical debt identification",
        "Remediation roadmap",
        "Effort estimation",
        "Stakeholder reporting",
      ],
    },
  ],

  trainersIntro:
    "Consulting sessions are led by a trainer who has delivered client engagements rather than only configured orgs. Your engagement simulation is challenged the way a client challenges a design — including on the estimate.",

  careerOutcomes: {
    paragraphs: [
      "Salesforce consulting hiring in Pune runs across the services majors' Salesforce practices and the Salesforce-native partner network, both of which staff consultants continuously. Postings appear as Salesforce Consultant, Functional Consultant, Sales Cloud Consultant, Service Cloud Consultant and Implementation Consultant.",
      "Progression is driven by implementation breadth more than by years served — five client orgs teaches more than one org for five years, because the range of problems is what senior roles pay for. From consulting the routes are practice lead, engagement manager, or the architect track for those who want technical depth rather than commercial ownership.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Consultant",
      "Salesforce Functional Consultant",
      "Sales Cloud Consultant",
      "Service Cloud Consultant",
      "Salesforce Implementation Consultant",
      "Salesforce Practice Lead (with experience)",
    ],
  },

  modesAndDuration: {
    duration: "3 months (11 weeks) for the weekday and online tracks; 13 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "Trailhead and trailmixes (free)",
        "Process-mapping and estimation templates",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 13 weeks rather than 11 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Consultant sits in the upper band of our catalogue, reflecting a three-month duration and the seniority of the trainer required. The Sales Cloud and Service Cloud Consultant examination fees are paid by you directly to Salesforce when you choose to sit, and are never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹40,000 – ₹58,000 (typical band) plus Salesforce examination fees, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge. For this track it looks different from our entry courses: you already have platform experience, so the work is repositioning — turning an administrator or analyst CV into a consulting one, and rehearsing the engagement stories a partner interview explores.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 9 — CV repositioned from administrator or analyst to consulting",
      "Week 10 — engagement simulation reviewed and presentation rehearsed",
      "Week 10 — first mock interview on design and estimation scenarios",
      "Week 11 — second mock interview on client-handling scenarios",
      "Week 11 — certification-readiness check for Sales or Service Cloud Consultant",
      "Post-course weeks 1–4 — introductions to consulting partners and services practices",
      "Post-course weeks 5–24 — weekly placement-cell check-ins",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Consultant or Architect — which progression fits?",
    paragraphs: [
      "Both are progression tracks and neither is a fresher destination. The consultant path takes you toward commercial and client ownership: scoping, designing, delivering and being accountable for an outcome someone is paying for. The architect path takes you toward technical ownership: integration, data and security architecture across a large estate.",
      "Choose consulting if the part you enjoy is the conversation, the design trade-off and the delivery. Choose architecture if the part you enjoy is the system, and you would rather be responsible for whether a platform scales than for whether a client is happy.",
      "The timelines differ substantially. Consulting is reachable at around two years of platform experience. Architecture, as our career guide states, is realistically a five to eight year target. Many people take consulting first and move to architecture later — the delivery experience makes the architecture judgement better, not worse.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "This course assumes existing Salesforce experience — roughly two years administering, analysing or implementing on the platform. That is a real gate rather than a suggestion: the course teaches delivery craft on top of platform knowledge and does not teach the platform itself. Our Salesforce Career Guide 2026 states plainly that consulting is a progression role, and we would rather turn an application away than take a fee for a course somebody cannot yet use. If you are earlier than that, the Administrator or Business Analyst path is the right starting point and this remains available afterwards.",
    ],
    suggestedSteps: [
      "Confirm you meet the experience gate — roughly two years administering, analysing or implementing",
      "Read the Salesforce Career Guide 2026 on our blog for how the eight paths connect",
      "Book a counselling session; for this track it doubles as a readiness check",
      "Check the upcoming batch dates and pick a mode",
      "Enrol, and bring a real project you have worked on — the course uses it",
    ],
  },

  faqs: [
    {
      question: "Can a fresher take the Salesforce Consultant course?",
      answer:
        "No, and we will say so at the counselling session rather than take the fee. Our Salesforce Career Guide 2026 states plainly that consulting is a progression role, not an entry role, and this course is built on that assumption — it teaches delivery craft on top of platform knowledge rather than teaching the platform. Start with the Administrator or Business Analyst path; this one remains available in two years.",
    },
    {
      question: "How much experience do I actually need?",
      answer:
        "Roughly two years administering, analysing or implementing on Salesforce. The gate is not the number itself but what it stands for: you should have configured real orgs, met real stakeholders and seen at least one thing go wrong in production. A candidate with eighteen months of varied implementation work is better prepared than one with three years maintaining a single stable org.",
    },
    {
      question: "Which consultant certification should I take?",
      answer:
        "Sales Cloud Consultant or Service Cloud Consultant, depending on where your delivery experience sits — this course prepares for both. Both assume the Administrator credential as a foundation, so hold that first. The consultant exams are scenario-heavy and test design judgement rather than feature recall, which is why the course is built around an engagement simulation.",
    },
    {
      question: "Is consulting only about the platform, or also about the client?",
      answer:
        "Mostly the client, which is what surprises people moving up from administration. The platform skill is assumed at this level. What you are paid for is scoping realistically, designing something maintainable, managing stakeholders who disagree, and landing change with people who did not ask for it. Client communication gets a full module here for exactly that reason.",
    },
    {
      question: "Do consultants need to know how to code?",
      answer:
        "Not to write it, but enough to scope it. A consultant who cannot tell whether a requirement needs Flow or Apex gives estimates that are wrong, and one who cannot assess an integration cannot commit to a timeline. This course teaches that judgement without teaching development — if you want to write the code, the Developer or Architect paths are the fit.",
    },
    {
      question: "What if I want to stay technical instead?",
      answer:
        "Take the Architect path rather than this one. Consulting moves you toward commercial and client ownership; architecture moves you toward technical ownership of integration, data and security across an estate. Both are progression tracks, but they lead to genuinely different working days, and the choice is worth making deliberately rather than drifting into.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to move into Salesforce consulting?",
    paragraph:
      "This is a progression track for people who already work on the platform. Three months from now you can have a full engagement simulation you presented and defended, a rescue assessment in your portfolio, a CV repositioned for consulting, and a clear run at the Sales or Service Cloud Consultant exam. Book a counselling session — for this course it doubles as a readiness check, and we will tell you honestly if you are not there yet.",
  },
};
