import type { CourseRichContent } from "./types";

/**
 * Salesforce Business Analyst — rich content overlay.
 *
 * Path 3 of the eight in the Salesforce Career Guide 2026. The translation
 * role between business and build teams, aimed at the BBA, MBA, existing
 * business analysts and project coordinators the guide names.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceBusinessAnalystTrainingInPune: CourseRichContent = {
  intro:
    "A Salesforce Business Analyst is the translator between what a business asks for and what a build team can deliver. The work is requirement gathering, stakeholder management, process mapping, user stories with acceptance criteria, and enough platform literacy to know when a request is a five-minute configuration and when it is a three-week integration. This two-and-a-half-month programme teaches the analysis craft alongside the Salesforce knowledge that makes it credible, aligned to the Salesforce Certified Business Analyst credential, and finishes with a full requirements pack for a real scenario.",

  whyLearn: {
    heading: "Why Learn Salesforce Business Analysis in Pune in 2026",
    paragraphs: [
      "Every Salesforce implementation in Pune fails or succeeds on requirements long before it fails or succeeds on code, and the business analyst is the role that owns that. Services majors and consulting partners both staff analysts on every delivery, and the role is unusually accessible to people from commerce, management and functional backgrounds because its core skill is asking better questions rather than writing better code.",
      "What makes the Salesforce variant of this role distinct from generic business analysis is platform literacy. An analyst who does not know that a master-detail relationship cannot be changed later, or that a roll-up summary has constraints, writes user stories the build team has to send back. This course teaches enough of the platform to make your requirements buildable, which is precisely the difference clients pay for.",
      "The role also sits at a genuinely useful junction. Analysts move into consulting once they have implementation experience, into product ownership, or into administration if they want to build as well as specify. Our career guide places it as an entry-accessible path with strong progression, and that is a fair description of the Pune market.",
    ],
    keyPoints: [
      "Accessible to BBA, MBA and functional professionals without programming",
      "Aligned to the Salesforce Certified Business Analyst credential",
      "Platform literacy taught alongside analysis craft, which is what makes requirements buildable",
      "Staffed on effectively every Salesforce delivery in Pune",
      "Direct progression into consulting and product ownership",
      "Indicative 1–3 year band ₹6–12 LPA",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "BBA, MBA and commerce graduates entering the technology industry",
      "Existing business analysts adding a platform specialisation",
      "Project coordinators and functional professionals moving into delivery roles",
      "Salesforce administrators who prefer the requirements side to the configuration side",
      "Domain professionals — sales operations, service, HR — moving into a Salesforce role",
    ],
    notForYou: [
      "Anyone wanting to build rather than specify — take the Administrator or Developer path",
      "Candidates uncomfortable with stakeholder conversation, since the role is mostly conversation",
      "Learners expecting a purely technical curriculum; roughly half of this course is craft rather than platform",
    ],
  },

  curriculum: [
    {
      title: "The Business Analyst Role & Salesforce Delivery",
      weekRange: "Week 1",
      description:
        "What the role actually does on a Salesforce project, and where it sits between the client, the administrator, the developer and the project manager. Delivery methodologies — agile, waterfall and the hybrid most Pune consulting partners actually run — and the artefacts expected at each stage.\n\nYou set up a Developer Edition org in the first session, because an analyst who has never configured anything writes requirements that cannot be built.",
      topics: [
        "The analyst's remit and its boundaries",
        "Where the role sits in a delivery team",
        "Agile, waterfall and hybrid delivery",
        "Sprints, ceremonies and the analyst's part in each",
        "Artefacts expected at each stage",
        "Setting up your own Salesforce org",
        "Stakeholder types and their different concerns",
        "Reading a statement of work",
      ],
    },
    {
      title: "Salesforce Platform Literacy for Analysts",
      weekRange: "Weeks 1–2",
      description:
        "Enough platform to make your requirements buildable. Objects, fields, relationships and record types; the security model at concept level; declarative automation and what Flow can and cannot do; reports and dashboards.\n\nThe emphasis throughout is on constraints rather than features — which decisions are hard to reverse, what a roll-up summary requires, why a request that sounds simple may not be. Knowing the boundary is the analyst's value.",
      topics: [
        "Objects, fields and relationships",
        "Record types and page layouts",
        "Profiles, permission sets and sharing at concept level",
        "What Flow can and cannot do",
        "Reports, dashboards and reporting constraints",
        "Standard Sales and Service Cloud processes",
        "Decisions that are hard to reverse",
        "AppExchange and build-versus-buy",
      ],
    },
    {
      title: "Requirement Elicitation & Stakeholder Management",
      weekRange: "Week 3",
      description:
        "The craft half of the role. Interview technique, workshop facilitation, observation and document analysis; managing stakeholders who disagree with each other; and the specific skill of getting to the actual problem when you have been handed a proposed solution.\n\nYou practise on live role-play scenarios with deliberately incomplete and contradictory briefs, which is closer to the job than any tidy case study.",
      topics: [
        "Interview technique and open questioning",
        "Workshop facilitation and getting a room to decide",
        "Observation and document analysis",
        "Getting behind a proposed solution to the problem",
        "Managing conflicting stakeholders",
        "Handling scope creep in the conversation",
        "Stakeholder mapping and influence",
        "Recording decisions so they hold",
      ],
    },
    {
      title: "Business Process Mapping & Analysis",
      weekRange: "Week 4",
      description:
        "Turning what people say into something a team can build against. As-is and to-be process mapping, swimlanes, BPMN basics, and the discipline of mapping what actually happens rather than what the policy says happens.\n\nGap analysis, process improvement and the honest judgement about which inefficiencies are worth automating — because automating a bad process makes it faster and no better.",
      topics: [
        "As-is and to-be process mapping",
        "Swimlane diagrams and BPMN basics",
        "Mapping actual behaviour, not documented policy",
        "Gap analysis and prioritisation",
        "Root-cause analysis",
        "Deciding what is worth automating",
        "Process documentation standards",
        "Validating a map with the people who do the work",
      ],
    },
    {
      title: "User Stories, Acceptance Criteria & Backlog",
      weekRange: "Week 5",
      description:
        "The artefact the build team actually works from. Writing user stories that carry intent rather than a UI instruction, acceptance criteria that are testable, and the INVEST characteristics that separate a workable story from a wish.\n\nBacklog management, prioritisation frameworks such as MoSCoW and weighted scoring, epics and story mapping, and estimation participation. You write a full backlog for the scenario you mapped in week four.",
      topics: [
        "User story structure and intent",
        "Testable acceptance criteria",
        "The INVEST characteristics",
        "Epics, features and story mapping",
        "Backlog grooming and refinement",
        "MoSCoW and weighted prioritisation",
        "Non-functional requirements",
        "Participating in estimation without owning it",
        "Traceability from requirement to story",
      ],
    },
    {
      title: "Data Requirements, Migration & Reporting Analysis",
      weekRange: "Week 6",
      description:
        "The parts of a Salesforce project that most often go wrong late. Data requirements and modelling from a business perspective; data quality rules; and migration analysis — source systems, mapping, cleansing and the reconciliation nobody plans time for.\n\nReporting requirements are treated as a first-class deliverable rather than an afterthought, since a report that cannot be built because of how the data was modelled is a requirements failure, not a reporting one.",
      topics: [
        "Data requirements from a business perspective",
        "Field-level requirements and picklist governance",
        "Data quality rules and ownership",
        "Migration source analysis and mapping",
        "Cleansing, deduplication and reconciliation",
        "Reporting requirements as a deliverable",
        "Reporting constraints that follow from the data model",
        "Data retention and privacy considerations",
      ],
    },
    {
      title: "Solution Design Participation & Documentation",
      weekRange: "Week 7",
      description:
        "Contributing to how something gets built without pretending to be the architect. Evaluating declarative against programmatic options at a level that lets you challenge an estimate; build-versus-buy against AppExchange; and the trade-off conversations where an analyst earns their place.\n\nDocumentation covers functional specifications, solution design documents, configuration workbooks and the change log that stops a project's history being lost.",
      topics: [
        "Declarative versus programmatic, at analyst level",
        "Build, buy or configure — evaluating AppExchange",
        "Challenging an estimate constructively",
        "Functional specification writing",
        "Solution design documentation",
        "Configuration workbooks",
        "Decision logs and change history",
        "Handover documentation",
      ],
    },
    {
      title: "Testing, UAT & Change Management",
      weekRange: "Week 8",
      description:
        "Getting the built thing accepted. Test planning from acceptance criteria, writing test scripts business users can actually follow, coordinating user acceptance testing, and triaging defects against whether they are a bug or a missed requirement — a distinction that decides who pays.\n\nChange management covers training material, communication, adoption measurement and the reality that a technically successful Salesforce rollout nobody uses is a failed project.",
      topics: [
        "Test planning from acceptance criteria",
        "Writing test scripts for business users",
        "Coordinating and running UAT",
        "Defect triage — bug or missed requirement",
        "Sign-off and go-live readiness",
        "Training material and user guides",
        "Communication and adoption planning",
        "Measuring adoption after go-live",
        "Hypercare and post-go-live support",
      ],
    },
    {
      title: "Certification Preparation & Portfolio",
      weekRange: "Week 9 + placement prep",
      description:
        "Preparation for the Salesforce Certified Business Analyst credential — its sections, weightings and scenario question style — with timed mock papers and systematic work through wrong answers.\n\nAlongside it, the portfolio: a complete requirements pack from your scenario — process maps, user stories, acceptance criteria, a data mapping and a UAT plan — which is what an interviewer actually wants to see from an analyst rather than a certificate number.",
      topics: [
        "Certified Business Analyst exam sections and weightings",
        "Scenario question technique and pacing",
        "Timed mock papers and gap closure",
        "Assembling a requirements portfolio",
        "Presenting a process map at interview",
        "Resume and LinkedIn for analyst roles",
        "Mock interview — elicitation and stakeholder scenarios",
        "Mock interview — platform literacy questions",
        "Booking, proctoring and maintenance",
      ],
    },
    {
      title: "AI-Assisted Analysis & Agentforce Awareness",
      weekRange: "Final Week",
      description:
        "Where AI helps an analyst and where it misleads. Drafting user stories and acceptance criteria, summarising workshop notes, generating first-pass process documentation and test scripts — all reviewed, because an assistant will confidently invent a requirement nobody stated.\n\nAgentforce is covered at analyst level: what an agent, an action and grounding are, and what a business is actually asking for when it requests one. The career guide's caveat holds — AI sits on top of process and data understanding, not instead of it.",
      topics: [
        "Drafting user stories and acceptance criteria with AI",
        "Summarising workshops and interview notes",
        "Generating first-pass documentation and test scripts",
        "Reviewing for invented requirements",
        "Agentforce at analyst level — agents, actions, grounding",
        "What a business is really asking for when it requests AI",
        "Data quality as the prerequisite for useful AI",
        "AI governance questions an analyst should raise",
        "Confidentiality when using external AI tools",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-ba-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Nine-stage Salesforce Business Analyst learning path taught at Archer Infotech Pune: the analyst role and Salesforce delivery methodologies; platform literacy covering objects, security, Flow and reporting constraints; requirement elicitation and stakeholder management; business process mapping and gap analysis; user stories, acceptance criteria and backlog management; data requirements, migration and reporting analysis; solution design participation and documentation; testing, user acceptance testing and change management; and certification preparation with a requirements portfolio.",
    caption:
      "The order this course is taught in — platform literacy early, because requirements written without it cannot be built. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-business-analyst-syllabus-v1.pdf",
    title: "Salesforce Business Analyst Syllabus — Complete Module List",
    slug: "salesforce-business-analyst-syllabus",
    blurb:
      "All ten modules as a PDF — the analyst role in Salesforce delivery, platform literacy, elicitation and stakeholder management, process mapping, user stories and backlog, data and migration analysis, solution design participation, UAT and change management, certification preparation and AI-assisted analysis. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All ten modules in teaching order, each with its schedule, description and full topic list.",
          "The craft half of the role given equal weight to the platform half — elicitation, facilitation, stakeholder conflict and getting behind a proposed solution to the actual problem.",
          "Platform literacy framed around constraints rather than features, because knowing what is hard to reverse is where an analyst earns their place.",
          "A full requirements portfolio as the deliverable — process maps, user stories, acceptance criteria, data mapping and a UAT plan.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Business Analyst — the role this course is written for.",
          "Salesforce Functional Consultant, with implementation experience added.",
          "Product Owner on a Salesforce delivery team.",
          "CRM Analyst and Sales or Service Operations Analyst.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "End-to-End Requirements Pack",
      description:
        "Take a real business scenario and produce the complete analyst deliverable: stakeholder map, as-is and to-be process maps, a prioritised backlog of user stories with testable acceptance criteria, data requirements and a migration mapping, reporting requirements, and a UAT plan with test scripts. The artefact interviewers ask analysts to walk them through.",
      technologies: [
        "Process mapping and BPMN",
        "User stories and acceptance criteria",
        "Backlog prioritisation",
        "Data mapping",
        "UAT test scripts",
        "Your own Salesforce org",
      ],
    },
    {
      title: "Configure What You Specified",
      description:
        "Build the core of your own requirements pack in your Developer org — objects, relationships, record types, a Flow and a reporting pack. Not to become an administrator, but because specifying something and then building it is the fastest way to learn which of your requirements were unbuildable, and that lesson does not transfer from a lecture.",
      technologies: [
        "Custom objects and relationships",
        "Flow Builder",
        "Reports and dashboards",
        "Validation rules",
      ],
    },
  ],

  trainersIntro:
    "Sessions are led by a trainer who has run requirements on live Salesforce deliveries. Your requirements pack is reviewed the way a delivery lead would review it — including being sent back when a story is not buildable.",

  careerOutcomes: {
    paragraphs: [
      "Salesforce business analysts are staffed on effectively every implementation in Pune, across services majors, consulting partners and the captive centres of global enterprises. Postings appear as Salesforce Business Analyst, Salesforce Functional Analyst, CRM Analyst and increasingly as combined analyst-and-administrator roles at smaller firms.",
      "Progression from here is unusually good: analysts move into consulting once they have implementation experience, into product ownership, or into administration if they want to build as well as specify. What moves the band is domain depth, stakeholder credibility and enough platform knowledge to be trusted in a design conversation.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Business Analyst",
      "Salesforce Functional Analyst",
      "CRM Analyst",
      "Product Owner (Salesforce delivery)",
      "Junior Salesforce Consultant",
      "Sales or Service Operations Analyst",
    ],
  },

  modesAndDuration: {
    duration: "2.5 months (10 weeks) for the weekday and online tracks; 12 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "Trailhead and trailmixes (free)",
        "A process-mapping tool",
        "A backlog tool such as Jira",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 12 weeks rather than 10 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Business Analyst sits in the mid band of our catalogue, reflecting a two-and-a-half-month duration. The Salesforce Certified Business Analyst examination fee is paid by you directly to Salesforce when you choose to sit, and is never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹28,000 – ₹42,000 (typical band) plus the Salesforce examination fee, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week eight. By graduation your resume is rewritten for analyst job descriptions, your requirements pack is reviewed, and you have completed at least two mock interviews covering elicitation scenarios and platform literacy.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 8 — resume and LinkedIn rewritten for analyst roles",
      "Week 9 — requirements portfolio reviewed by the trainer",
      "Week 9 — first mock interview on elicitation and stakeholder scenarios",
      "Week 10 — second mock interview on platform literacy and process questions",
      "Week 10 — certification-readiness check",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Business Analyst or Administrator — which should you take first?",
    paragraphs: [
      "Take the Business Analyst path if the part you enjoy is working out what a business actually needs, running the conversation that gets there, and writing it down so a team can build it. Take the Administrator path if the part you enjoy is building the thing.",
      "Both are entry-accessible without programming, and both are named in our career guide as suiting non-IT graduates. The analyst role leans harder on communication and domain understanding; the administrator role leans harder on configuration judgement and platform depth.",
      "In practice the two overlap considerably at smaller firms, where one person does both, and separate cleanly at large consulting partners, where they are distinct staffed roles. If you are genuinely undecided, the counselling session is worth taking — the answer usually falls out of your existing background within ten minutes.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "No programming and no IT background is required. What matters is comfort holding a conversation with someone senior, patience with ambiguity, and willingness to write clearly — the deliverable of this role is a document someone else acts on. Graduates from commerce, management and arts backgrounds do well here, and existing analysts from any domain adapt quickly because the craft transfers and only the platform layer is new.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to confirm the analyst path fits your background",
      "Create a free Developer Edition org and click through a standard sales process",
      "Check the upcoming batch dates and pick a mode — classroom, live online or weekend",
      "Book a free counselling session if you are undecided between analyst and administrator",
      "Enrol, and bring a laptop to session one",
    ],
  },

  faqs: [
    {
      question: "Do I need a technical background to be a Salesforce Business Analyst?",
      answer:
        "No. The core skill is asking better questions and writing down the answers so a build team can act on them, and BBA, MBA and commerce graduates do this well. What you do need is platform literacy — enough Salesforce knowledge to know when a request is a five-minute configuration and when it is a three-week integration — and that is taught here in weeks one and two.",
    },
    {
      question: "How is this different from a general business analyst course?",
      answer:
        "Roughly half of it is the same craft — elicitation, process mapping, user stories, UAT. The other half is Salesforce-specific: the object model, the security model, what Flow can and cannot do, reporting constraints, and the decisions that are hard to reverse. That platform half is what makes your requirements buildable, and it is what clients pay a Salesforce analyst for over a generic one.",
    },
    {
      question: "Will I configure anything, or only write documents?",
      answer:
        "You configure. One of the two projects has you build the core of your own requirements pack in your Developer org — not to become an administrator, but because specifying something and then building it is the fastest way to discover which of your requirements were unbuildable. That lesson does not transfer from a lecture.",
    },
    {
      question: "Which certification does this course prepare me for?",
      answer:
        "The Salesforce Certified Business Analyst credential, which is the role-based credential for this path. Some analysts also take the Administrator certification to demonstrate platform depth, and it is a reasonable addition if you came in without configuration background — but the Business Analyst credential is the one written for this role.",
    },
    {
      question: "Can I move into consulting from a business analyst role?",
      answer:
        "Yes, and it is the most common progression. Our career guide is explicit that the consultant role is a progression rather than an entry point, and business analysis is one of the two backgrounds it names as feeding into it — the other being experienced administration. Expect two to three years of implementation experience before consulting roles open.",
    },
    {
      question: "Is this role at risk from AI?",
      answer:
        "The drafting parts are already being assisted — user stories, first-pass documentation, workshop summaries — and the final module covers doing that responsibly. What is not being automated is sitting in a room with stakeholders who disagree, getting behind a proposed solution to the actual problem, and being accountable for a requirement someone builds against. Analysts who use AI for the drafting and keep the judgement are in a stronger position than before.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Business Analyst training in Pune?",
    paragraph:
      "Two and a half months from now you can have a complete requirements pack for a real scenario, a configured org proving your requirements were buildable, mock interviews behind you, and a clear run at the Salesforce Certified Business Analyst exam. No programming background is needed. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
