import type { CourseRichContent } from "./types";

/**
 * Salesforce Marketing Cloud — rich content overlay.
 *
 * Path 6 of the eight in the Salesforce Career Guide 2026, which describes
 * it as one of the few genuinely non-technical high-value specialisations.
 * Aimed at the MBA Marketing graduates, digital marketers and CRM
 * professionals the guide names.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceMarketingCloudTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Marketing Cloud is the customer engagement platform — journeys, email, mobile messaging, audience segmentation, personalisation and campaign analytics. Our Salesforce Career Guide 2026 calls it one of the few genuinely non-technical high-value specialisations in the ecosystem, and that is accurate: the work is marketing judgement supported by platform capability rather than engineering. Three months, taught hands-on, aligned to the Marketing Cloud Email Specialist and Administrator credentials, finishing with a multi-channel journey you designed, built and measured.",

  whyLearn: {
    heading: "Why Learn Salesforce Marketing Cloud in Pune in 2026",
    paragraphs: [
      "Marketing Cloud is where marketing skill converts into a technology salary without requiring a technology degree. The platform is deep, the certifications are respected, and the supply of people who genuinely understand both marketing strategy and the platform is persistently short — which is why our career guide flags it as a high-value specialisation that stays open to non-technical backgrounds.",
      "Pune demand comes from the consulting partners running Marketing Cloud implementations, services majors staffing marketing-technology practices, and the enterprises running their own customer engagement in-house. Postings appear as Marketing Cloud Consultant, Marketing Automation Specialist and Email Specialist, and they are noticeably less crowded than general digital-marketing openings.",
      "The honest note is that Marketing Cloud is a large and somewhat idiosyncratic product suite that grew partly by acquisition, and parts of it look and behave differently from core Salesforce. That unfamiliarity is exactly why the specialisation pays — but it means the learning curve is real and the course is hands-on throughout rather than conceptual.",
    ],
    keyPoints: [
      "One of the few genuinely non-technical high-value Salesforce specialisations",
      "Suits MBA Marketing, digital marketers and CRM professionals",
      "Aligned to the Email Specialist and Marketing Cloud Administrator credentials",
      "Less crowded than general digital-marketing hiring in Pune",
      "AMPscript and SQL taught at the level the role actually needs",
      "Indicative 1–3 year band ₹6–12 LPA",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "MBA Marketing graduates entering marketing technology",
      "Digital marketers moving from campaign execution into platform ownership",
      "CRM and marketing automation professionals from other tools",
      "Salesforce administrators adding a marketing specialisation",
      "Anyone who wants a technology salary without a coding-first career",
    ],
    notForYou: [
      "Anyone wanting core Salesforce CRM configuration — take the Administrator path",
      "Candidates expecting a general digital-marketing course; this is one platform in depth",
      "Learners unwilling to touch AMPscript or SQL at all, since both appear at a practical level",
    ],
  },

  curriculum: [
    {
      title: "Marketing Cloud Architecture & Setup",
      weekRange: "Week 1",
      description:
        "What the platform actually is, which surprises people expecting core Salesforce. Business units, roles and permissions, the account hierarchy, and the Setup areas you will live in. Data Extensions as the central concept — how Marketing Cloud stores data and why it differs from Salesforce objects.\n\nYou get access to a practice environment and configure it from empty, because inheriting someone else's configuration teaches you nothing about why it is that way.",
      topics: [
        "Marketing Cloud Studios and Builders",
        "Business units and the account hierarchy",
        "Roles, permissions and user setup",
        "Data Extensions versus Salesforce objects",
        "Sendable and non-sendable Data Extensions",
        "Contact model and the contact key",
        "Setup navigation and where things live",
        "Configuring an environment from empty",
      ],
    },
    {
      title: "Email Studio & Content Builder",
      weekRange: "Weeks 2–3",
      description:
        "The core craft. Building emails in Content Builder, reusable content blocks, templates, and responsive design that survives the range of clients real recipients use. Personalisation strings, dynamic content and preview-and-test against a subscriber.\n\nDeliverability gets its own treatment because it decides whether any of the rest matters: sender authentication, reputation, list hygiene, spam-trigger avoidance and what actually happens when engagement drops.",
      topics: [
        "Content Builder, blocks and templates",
        "Responsive email design across clients",
        "Personalisation strings and dynamic content",
        "Preview, test sends and rendering checks",
        "Subscriber lists versus Data Extensions",
        "Sender authentication and reputation",
        "List hygiene and re-engagement",
        "Spam triggers and deliverability practice",
        "A/B testing email content",
      ],
    },
    {
      title: "Audience Segmentation, Data & SQL",
      weekRange: "Week 4",
      description:
        "Getting the right message to the right people, which is a data problem before it is a creative one. Data Extensions in depth, relationships between them, filtered Data Extensions and Audience Builder.\n\nSQL is introduced at exactly the level this role needs — SELECT, JOIN, WHERE and aggregation inside Query Activities — because segmentation beyond the basics is written in SQL, and marketers who avoid it stay limited to what the interface offers.",
      topics: [
        "Data Extension design and relationships",
        "Import, file transfer and automation",
        "Filtered Data Extensions",
        "SQL SELECT, JOIN, WHERE and aggregation",
        "Query Activities and scheduling",
        "Audience Builder and attribute groups",
        "Suppression and exclusion logic",
        "Data retention and privacy compliance",
      ],
    },
    {
      title: "Journey Builder & Automation Studio",
      weekRange: "Weeks 5–6",
      description:
        "Where campaigns become programmes. Journey Builder — entry sources, activities, decision splits, waits, engagement splits and goals — and the design thinking behind a journey that responds to behaviour rather than pushing a fixed sequence.\n\nAutomation Studio covers scheduled and file-triggered automations, imports, queries, filters and extracts. Together these are the operational backbone, and the module closes on testing a journey properly before real people enter it.",
      topics: [
        "Journey Builder entry sources and admission",
        "Activities, waits and decision splits",
        "Engagement splits and behavioural branching",
        "Goals, exit criteria and journey versioning",
        "Automation Studio activities",
        "Scheduled and file-drop automations",
        "Multi-step campaign orchestration",
        "Testing a journey before it goes live",
        "Journey reporting and troubleshooting",
      ],
    },
    {
      title: "AMPscript & Dynamic Personalisation",
      weekRange: "Week 7",
      description:
        "The scripting layer, taught at the level a marketer genuinely needs rather than as programming. AMPscript variables, functions, conditionals and lookups; retrieving related data into an email; and formatting dates, numbers and names without producing the personalisation failures everyone has received.\n\nSSJS and Guided Template Language are introduced briefly for awareness. The bar set here is being able to read, adapt and debug AMPscript, which is what the role actually asks for.",
      topics: [
        "AMPscript syntax, variables and output",
        "Conditionals and looping",
        "Lookup functions and related data",
        "Formatting dates, numbers and names",
        "Personalisation failure modes",
        "Debugging AMPscript in a preview",
        "Guided Template Language basics",
        "SSJS awareness and when it is used",
      ],
    },
    {
      title: "Mobile, Advertising & Cross-Channel",
      weekRange: "Week 8",
      description:
        "Beyond email. MobileConnect for SMS with the consent and compliance rules that govern it in India; MobilePush for app messaging; Advertising Studio for audience activation into paid channels; and Social Studio awareness.\n\nThe framing is orchestration: a journey that reaches someone by SMS after they ignored two emails is a different and better programme than three emails, and designing that is the skill.",
      topics: [
        "MobileConnect and SMS campaigns",
        "Consent, opt-in and Indian compliance rules",
        "MobilePush and in-app messaging",
        "Advertising Studio and audience activation",
        "Cross-channel journey design",
        "Channel selection and frequency capping",
        "Preference centres and unsubscribe handling",
        "Coordinating channels without fatiguing a contact",
      ],
    },
    {
      title: "Analytics, Attribution & Optimisation",
      weekRange: "Week 9",
      description:
        "Proving the programme worked. Tracking and engagement metrics, Datorama and Intelligence Reports awareness, and building reporting that answers a commercial question rather than displaying open rates.\n\nAttribution is treated honestly, including its limits — the shift away from open-rate reliability after privacy protections, and why last-touch attribution flatters email. Optimisation covers testing discipline and the difference between a real result and noise.",
      topics: [
        "Tracking, engagement and conversion metrics",
        "Why open rate became unreliable",
        "Reporting that answers a commercial question",
        "Datorama and Intelligence Reports awareness",
        "Attribution models and their limits",
        "A/B and multivariate testing discipline",
        "Distinguishing a result from noise",
        "Presenting campaign performance to stakeholders",
      ],
    },
    {
      title: "Campaign Build & Certification Preparation",
      weekRange: "Week 10 + placement prep",
      description:
        "A complete multi-channel journey you designed, built, tested and measured, documented as a campaign case study — which is what a Marketing Cloud interview actually explores.\n\nAlongside it, preparation for the Marketing Cloud Email Specialist and Administrator credentials: exam weightings, scenario question style, timed mocks and gap closure. Mock interviews cover journey design, segmentation and deliverability scenarios.",
      topics: [
        "End-to-end multi-channel campaign build",
        "Campaign case study documentation",
        "Email Specialist exam preparation",
        "Marketing Cloud Administrator exam preparation",
        "Timed mock papers and gap closure",
        "Mock interview — journey design scenarios",
        "Mock interview — segmentation and SQL scenarios",
        "Resume and LinkedIn for marketing technology roles",
      ],
    },
    {
      title: "AI in Marketing Cloud & Agentforce",
      weekRange: "Final Week",
      description:
        "Einstein features a marketer configures — send-time optimisation, engagement scoring, content selection — and what each actually needs to work: enough data, and data that is correct.\n\nAgentforce is covered at the level of what marketing teams are being sold and what it requires underneath, with the career guide's caveat intact. Generative assistance for subject lines and copy is covered with the obvious professional caution: everything reviewed, brand voice protected, nothing sent unread.",
      topics: [
        "Einstein send-time optimisation",
        "Einstein engagement scoring and content selection",
        "Data requirements for each Einstein feature",
        "Agentforce in a marketing context",
        "Generative assistance for copy and subject lines",
        "Protecting brand voice and reviewing output",
        "Consent, privacy and AI in marketing",
        "Advising honestly on AI readiness",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-marketing-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Nine-stage Salesforce Marketing Cloud learning path taught at Archer Infotech Pune: architecture and setup covering business units, Data Extensions and the contact model; Email Studio and Content Builder with deliverability; audience segmentation with Data Extensions and SQL; Journey Builder and Automation Studio; AMPscript and dynamic personalisation; mobile, advertising and cross-channel orchestration; analytics, attribution and optimisation; a campaign build with certification preparation; and AI features with Agentforce.",
    caption:
      "The order this course is taught in — the data model before the journeys, because segmentation is a data problem before it is a creative one. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-marketing-cloud-syllabus-v1.pdf",
    title: "Salesforce Marketing Cloud Syllabus — Complete Module List",
    slug: "salesforce-marketing-cloud-syllabus",
    blurb:
      "All nine modules as a PDF — Marketing Cloud architecture and Data Extensions, Email Studio and deliverability, segmentation with SQL, Journey Builder and Automation Studio, AMPscript, mobile and cross-channel, analytics and attribution, the campaign build with certification preparation, and Einstein and Agentforce in marketing. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All nine modules in teaching order, each with its schedule, description and full topic list.",
          "Deliverability treated as a first-class subject — authentication, reputation, list hygiene and what happens when engagement drops — because it decides whether anything else matters.",
          "SQL and AMPscript taught at the level the role genuinely needs, which is the boundary most marketing courses avoid and most job descriptions require.",
          "Attribution covered honestly, including why open rate became unreliable and how last-touch attribution flatters email.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Marketing Cloud Email Specialist — the usual entry credential and role.",
          "Marketing Automation Specialist and Marketing Cloud Administrator.",
          "Marketing Cloud Consultant at a Salesforce partner.",
          "Marketing technology roles inside enterprises running their own engagement.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Multi-Channel Onboarding Journey",
      description:
        "Design, build, test and measure a complete onboarding programme: segmentation from Data Extensions with SQL, a welcome email series in Content Builder, behavioural branching in Journey Builder, an SMS step for non-openers with consent handled correctly, AMPscript personalisation, and a reporting view that answers whether it worked. Documented as a campaign case study.",
      technologies: [
        "Journey Builder",
        "Email Studio and Content Builder",
        "Data Extensions and SQL",
        "AMPscript",
        "MobileConnect",
        "Campaign reporting",
      ],
    },
    {
      title: "Re-Engagement and List Hygiene Programme",
      description:
        "Take a deliberately degraded subscriber list — stale contacts, hard bounces, poor engagement — and build the programme that fixes it: suppression logic, a re-engagement journey, sunset rules for the unresponsive, and deliverability measurement before and after. The unglamorous work that separates a Marketing Cloud specialist from someone who sends emails.",
      technologies: [
        "Filtered Data Extensions",
        "Suppression and exclusion logic",
        "Journey Builder",
        "Deliverability metrics",
        "Automation Studio",
      ],
    },
  ],

  trainersIntro:
    "Sessions are led by a trainer who runs campaigns on the platform rather than only teaching it. Your journeys and queries are reviewed in a practice environment, including being asked why a segment is defined the way it is.",

  careerOutcomes: {
    paragraphs: [
      "Marketing Cloud hiring in Pune comes from the consulting partners running implementations, services majors staffing marketing-technology practices, and enterprises running engagement in-house. Postings appear as Marketing Cloud Email Specialist, Marketing Automation Specialist, Marketing Cloud Consultant and Campaign Manager, and they are noticeably less crowded than general digital-marketing openings.",
      "What moves the band is the combination our career guide points to for functional professionals: platform depth, data and segmentation ability, and business judgement about what a campaign is for. The specialists who progress fastest are those who stopped avoiding SQL and AMPscript early.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Marketing Cloud Email Specialist",
      "Marketing Automation Specialist",
      "Marketing Cloud Administrator",
      "Marketing Cloud Consultant",
      "Campaign Manager",
      "CRM Marketing Specialist",
    ],
  },

  modesAndDuration: {
    duration: "3 months (11 weeks) for the weekday and online tracks; 13 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "A Marketing Cloud practice environment",
        "Trailhead and trailmixes (free)",
        "Email rendering and testing tools",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 13 weeks rather than 11 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Marketing Cloud sits in the upper-mid band of our catalogue, reflecting a three-month duration and the practice environment required. Salesforce examination fees are paid by you directly to Salesforce when you choose to sit, and are never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹38,000 – ₹52,000 (typical band) plus Salesforce examination fees, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week nine. By graduation your resume is rewritten for marketing technology job descriptions, your campaign case study is reviewed, and you have completed mock interviews on journey design and segmentation scenarios.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 9 — resume and LinkedIn rewritten for marketing technology roles",
      "Week 10 — campaign case study reviewed and presentation rehearsed",
      "Week 10 — first mock interview on journey design scenarios",
      "Week 11 — second mock interview on segmentation, SQL and deliverability",
      "Week 11 — certification-readiness check for Email Specialist",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Marketing Cloud or a general digital marketing course?",
    paragraphs: [
      "A general digital marketing course is broader — SEO, paid media, social, analytics — and the skills transfer to any employer. Marketing Cloud is one platform in depth, and the skills are worth considerably more inside the Salesforce ecosystem than outside it.",
      "The trade is competition. General digital marketing openings in Pune attract very large candidate pools; Marketing Cloud openings attract small ones, because the intersection of marketing judgement and platform depth is genuinely uncommon. Our career guide flags precisely that as the reason this is a high-value specialisation.",
      "If you already work in marketing, this is a specialisation that raises your band without requiring you to become an engineer. If you are entirely new to marketing, learn the marketing first — the platform amplifies judgement and cannot substitute for it.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "No programming background is needed, and no core Salesforce experience is assumed. Marketing background helps considerably: this course teaches a platform for doing marketing, not marketing itself, and learners who already understand segmentation, campaign design and what a funnel is get far more from it. Comfort with spreadsheets is useful, and willingness to write basic SQL is genuinely required — it appears from week four and cannot be avoided in the role.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to see where the marketing path sits",
      "Complete a Trailhead Marketing Cloud basics module to check the platform appeals",
      "Check the upcoming batch dates and pick a mode",
      "Book a free counselling session if you are choosing between this and a general digital marketing course",
      "Enrol, and bring a laptop to session one",
    ],
  },

  faqs: [
    {
      question: "Is Marketing Cloud really non-technical?",
      answer:
        "Largely, and our career guide describes it as one of the few genuinely non-technical high-value Salesforce specialisations. You will not write Apex or build components. You will write basic SQL for segmentation from week four, and read and adapt AMPscript for personalisation in week seven. Both are taught from scratch at the level the role needs — but a learner unwilling to touch either will be limited to what the interface offers.",
    },
    {
      question: "Do I need core Salesforce experience first?",
      answer:
        "No. Marketing Cloud is architecturally quite separate from core Salesforce — it has its own data model built on Data Extensions rather than objects, its own permissions and its own interface. Core Salesforce knowledge helps when the two are integrated, but it is not a prerequisite, and plenty of Marketing Cloud specialists have never administered a Sales Cloud org.",
    },
    {
      question: "Which certification should I take first?",
      answer:
        "Marketing Cloud Email Specialist is the standard entry credential and what most Pune postings screen on. Marketing Cloud Administrator follows naturally and this course prepares for both. Consultant and Developer credentials exist for later specialisation, and the Developer one is genuinely technical — it is not the natural next step for a marketing background.",
    },
    {
      question: "Will I get a practice environment?",
      answer:
        "Yes. Marketing Cloud does not offer a free permanent developer edition the way core Salesforce does, so practice access is arranged as part of the course. That is one reason this track is priced where it is, and one reason we teach it hands-on rather than through demonstration — a Marketing Cloud specialist who has never built a journey does not get past a first interview.",
    },
    {
      question: "How much SQL do I need?",
      answer:
        "SELECT, JOIN, WHERE and basic aggregation, written inside Query Activities. That is genuinely all — no database administration and no optimisation. It is taught from scratch in week four and used throughout afterwards. Segmentation beyond what the interface offers is written in SQL, so avoiding it caps what you can do and what you can be hired for.",
    },
    {
      question: "Is email marketing still a career with AI writing copy?",
      answer:
        "Copy generation is the part being assisted, and the final module covers using it professionally. What is not being automated is deciding who should receive what and when, designing a journey that responds to behaviour, keeping a sender reputation healthy, and being accountable for a campaign's commercial result. Specialists who use AI for drafting and keep the judgement are in a stronger position than before.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Marketing Cloud training in Pune?",
    paragraph:
      "Three months from now you can have a multi-channel journey you designed, built and measured, a re-engagement programme with deliverability figures behind it, a documented campaign case study, and a clear run at the Marketing Cloud Email Specialist exam. No programming background needed. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
