import type { CourseRichContent } from "./types";

/**
 * Salesforce Developer — rich content overlay.
 *
 * Path 2 of the eight in the Salesforce Career Guide 2026. The engineering
 * path — Apex, Lightning Web Components, integration and DevOps — aimed at
 * the BE, BTech, MCA and working Java, .NET and Python developers the guide
 * names.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceDeveloperTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Developer is the engineering path through the ecosystem: Apex classes and triggers, asynchronous processing, SOQL and SOSL, Lightning Web Components, REST and SOAP integration, unit testing and deployment. Apex is deliberately Java-like, which is why our career guide notes that Java developers transition fastest of any background. This three-and-a-half-month programme assumes you can already program, teaches the platform's constraints properly — governor limits are not an afterthought here — and finishes with a deployed application in your own org, aligned to the Salesforce Platform Developer I exam.",

  whyLearn: {
    heading: "Why Learn Salesforce Development in Pune in 2026",
    paragraphs: [
      "Salesforce development pays materially more than administration for the same years of experience, and the reason is supply: the ecosystem is full of administrators and short of people who can write Apex that survives governor limits, build Lightning Web Components properly, and integrate an org with the systems around it. Pune's services majors and Salesforce consulting partners both hire developers continuously, and integration experience in particular is a reliable premium.",
      "For a working Java or .NET developer, this is one of the shortest credible route changes available. Apex borrows Java's syntax and object model, SOQL reads like SQL with relationship traversal, and the development lifecycle — source control, testing, deployment — is the one you already practise. What is genuinely new is the platform's opinionated constraints, and those are what this course spends its time on.",
      "The honest caveat is that development on Salesforce is not general software engineering with a different logo. The platform decides how much you may query, how many records you may touch in a transaction, and when your code runs at all. A developer who brings unmodified habits from a Spring Boot codebase writes Apex that passes tests in a small org and fails on the first real dataset. Governor limits and bulkification are taught early here for exactly that reason.",
    ],
    keyPoints: [
      "The best-paid entry route in the ecosystem for people who can already code",
      "Apex is Java-like — Java and .NET developers transition fastest",
      "Aligned to the Salesforce Platform Developer I exam",
      "Governor limits and bulkification taught early, not as a footnote",
      "Integration and DevOps included, which is where the salary premium sits",
      "Indicative 1–3 year band ₹6–12 LPA, rising sharply with integration depth",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "BE, BTech, MCA and BCA graduates with a programming background",
      "Working Java, .NET or Python developers moving into the Salesforce ecosystem",
      "Salesforce administrators who want to add Apex and Lightning Web Components",
      "Developers at services majors being moved onto a Salesforce practice",
      "Anyone who has completed our Salesforce Administrator course and wants the engineering path",
    ],
    notForYou: [
      "Complete non-programmers — take the Salesforce Administrator path first, then return",
      "Anyone hoping to skip administration entirely; Apex written without understanding the security and object model breaks things quietly",
      "Candidates wanting a purely functional or business-facing role — the Business Analyst or Consultant path fits better",
      "Learners unwilling to write code between sessions, since Apex is learned by writing it",
    ],
  },

  curriculum: [
    {
      title: "Platform Foundations for Developers",
      weekRange: "Week 1",
      description:
        "The administrator layer a developer cannot skip, compressed into a week. Objects, fields, relationships, record types and the security model — profiles, permission sets, organisation-wide defaults and sharing — because Apex runs in this context and code that ignores it either fails or leaks data.\n\nYou set up a Developer Edition org, install the Salesforce Extensions for VS Code, and get a working local development loop before any Apex is written.",
      topics: [
        "Objects, fields and relationships",
        "Record types and page layouts",
        "Profiles, permission sets and sharing",
        "Organisation-wide defaults and record access",
        "Developer Edition org setup",
        "VS Code and Salesforce Extensions",
        "Salesforce CLI and authorising an org",
        "Metadata, source format and the project structure",
        "Declarative before programmatic — when not to write code",
      ],
    },
    {
      title: "Apex Fundamentals",
      weekRange: "Weeks 2–3",
      description:
        "The language itself. Data types, collections — lists, sets and maps, with maps given real attention because they are how bulkified Apex avoids queries in loops — control flow, classes, interfaces, inheritance and access modifiers.\n\nsObjects and DML follow: insert, update, upsert, delete, and the difference between the database methods and the DML statements when partial success matters. Exception handling and custom exceptions close the module.",
      topics: [
        "Data types, variables and constants",
        "Lists, sets and maps",
        "Classes, objects, constructors and properties",
        "Interfaces, inheritance and access modifiers",
        "sObjects and field access",
        "DML statements and Database methods",
        "Partial success and allOrNone",
        "Exception handling and custom exceptions",
        "Apex naming and code conventions",
      ],
    },
    {
      title: "SOQL, SOSL & Relationship Queries",
      weekRange: "Week 4",
      description:
        "Getting data out of the platform. SOQL syntax, filtering, ordering and limits; parent-to-child and child-to-parent relationship queries, which are the platform's substitute for joins and behave differently from them; aggregate queries and GROUP BY.\n\nSOSL covers text search across objects. The module closes on query plans, selectivity and indexing — the material that decides whether a query survives a million records or times out on them.",
      topics: [
        "SOQL syntax, filters and ordering",
        "Parent-to-child and child-to-parent traversal",
        "Aggregate queries and GROUP BY",
        "Date literals and dynamic SOQL",
        "SOSL for cross-object text search",
        "Query selectivity and custom indexes",
        "The query plan tool",
        "Avoiding queries inside loops",
        "Binding variables and injection safety",
      ],
    },
    {
      title: "Triggers, Bulkification & Governor Limits",
      weekRange: "Week 5",
      description:
        "The module that separates Apex that works from Apex that ships. Trigger context variables, before and after events, and the order of execution — which is worth memorising because a surprising number of production defects are explained by it.\n\nGovernor limits are covered as a design constraint rather than a list: what they are, why they exist in a multi-tenant platform, and how bulkification, collections and a single trigger per object keep you inside them. You deliberately breach a limit, read the error, and fix the design.",
      topics: [
        "Trigger events and context variables",
        "The order of execution",
        "One trigger per object and the handler pattern",
        "Bulkification and processing collections",
        "Governor limits and why they exist",
        "Queries and DML outside loops",
        "Recursion control and static variables",
        "Trigger frameworks",
        "Reading and fixing a limit exception",
      ],
    },
    {
      title: "Asynchronous Apex",
      weekRange: "Week 6",
      description:
        "Work that cannot happen in a synchronous transaction. Future methods for simple offloading and callouts; Queueable for chaining and complex state; Batch Apex for large data volumes with its start, execute and finish structure; and Scheduled Apex for recurring jobs.\n\nThe judgement taught is which to reach for, since they have different limits, different debuggability and different failure modes. Platform events and change data capture close the module as the event-driven alternative.",
      topics: [
        "Future methods and their constraints",
        "Queueable Apex and job chaining",
        "Batch Apex — start, execute, finish",
        "Batch size, scope and state",
        "Scheduled Apex and cron expressions",
        "Choosing between the asynchronous options",
        "Monitoring jobs and handling failures",
        "Platform events and event-driven design",
        "Change Data Capture",
      ],
    },
    {
      title: "Lightning Web Components",
      weekRange: "Weeks 7–8",
      description:
        "The modern front end. LWC structure — HTML template, JavaScript class, metadata — reactivity, properties and the decorators that drive it. Component composition, events for child-to-parent communication, and the Lightning Message Service for components that are not related.\n\nData access covers wire adapters, imperative Apex calls, and the Lightning Data Service, with a clear rule for choosing. Navigation, base components, styling with the Salesforce Lightning Design System, and Jest testing close the module.",
      topics: [
        "LWC file structure and metadata",
        "Templates, directives and conditional rendering",
        "Reactivity, @api, @track and getters",
        "Component composition and slots",
        "Custom events and event bubbling",
        "Lightning Message Service",
        "Wire adapters versus imperative Apex",
        "Lightning Data Service and record forms",
        "Navigation and base components",
        "SLDS styling and accessibility",
        "Jest tests for components",
      ],
    },
    {
      title: "Integration — REST, SOAP, Callouts & Platform APIs",
      weekRange: "Week 9",
      description:
        "Where the salary premium sits. Salesforce as an API provider — REST, SOAP, Bulk and Composite APIs, and when each is right — and as an API consumer: named credentials, external credentials, callouts from Apex, and the callout limits that shape a design.\n\nAuthentication covers OAuth flows, connected apps and the JWT bearer flow for server-to-server integration. Error handling, retries and idempotency close the module, along with an honest note on when middleware belongs in the architecture instead of more Apex.",
      topics: [
        "REST, SOAP, Bulk and Composite APIs",
        "Choosing the right API for a volume",
        "Named credentials and external credentials",
        "HTTP callouts from Apex",
        "Callout limits and asynchronous patterns",
        "OAuth flows and connected apps",
        "JWT bearer flow for server-to-server",
        "Apex REST and custom web services",
        "Error handling, retries and idempotency",
        "When middleware is the better answer",
      ],
    },
    {
      title: "Testing, Debugging & Code Quality",
      weekRange: "Week 10",
      description:
        "The platform enforces test coverage before deployment, which turns testing from a discipline into a gate — and produces a great deal of low-value Apex written purely to reach the number. This module covers writing tests that are actually worth having: test data factories, bulk assertions, negative cases, and testing as a user with runAs.\n\nDebugging covers debug logs, log levels, the Apex Replay Debugger and checkpoints. Static analysis, code review and Apex design patterns close the module.",
      topics: [
        "Apex test classes and assertions",
        "Test data factories and @testSetup",
        "Bulk testing with realistic volumes",
        "Negative tests and exception assertions",
        "runAs and testing under different permissions",
        "Coverage requirements and gaming them",
        "Debug logs, levels and reading a log",
        "Apex Replay Debugger and checkpoints",
        "Static analysis and code review",
        "Common Apex design patterns",
      ],
    },
    {
      title: "Deployment, Salesforce DX & DevOps",
      weekRange: "Week 11",
      description:
        "Getting work from your org to production safely. Sandboxes and their refresh behaviour; change sets and their limits; then Salesforce DX properly — source-driven development, scratch orgs, the project structure, and unlocked packages.\n\nVersion control with Git, branching strategy for Salesforce teams, and a CI pipeline that validates a deployment before it runs. The module closes on release management across the three annual Salesforce releases, which is a real operational obligation rather than a footnote.",
      topics: [
        "Sandbox types and refresh behaviour",
        "Change sets and where they run out",
        "Salesforce DX and source-driven development",
        "Scratch orgs and org shape",
        "Unlocked and managed packages",
        "Git branching for Salesforce teams",
        "CI pipelines and validation deployments",
        "Destructive changes and metadata dependencies",
        "The three annual releases and impact assessment",
      ],
    },
    {
      title: "Capstone Build & Platform Developer I Preparation",
      weekRange: "Weeks 12–13 + placement prep",
      description:
        "A full build in your own org — data model, triggers with a handler framework, asynchronous processing, Lightning Web Components, an integration and a test suite — deployed through a pipeline you configured, with a README explaining the architecture.\n\nAlongside it, structured preparation for the Platform Developer I exam: section weightings, scenario question style, timed mock papers and systematic work through wrong answers. Mock interviews cover Apex, LWC, governor limits and integration scenarios.",
      topics: [
        "Capstone implementation and deployment",
        "Architecture documentation and README",
        "Platform Developer I exam weightings",
        "Scenario question technique and pacing",
        "Timed mock papers and gap closure",
        "Mock interview — Apex and governor limits",
        "Mock interview — LWC and integration",
        "Walking a panel through your own code",
        "Resume and LinkedIn for developer roles",
        "Booking, proctoring and maintenance",
      ],
    },
    {
      title: "AI-Assisted Salesforce Development & Agentforce",
      weekRange: "Final Week",
      description:
        "AI in the development loop, and where Agentforce fits for a developer. Using assistants to scaffold Apex and LWC, generate test classes, explain inherited code and draft documentation — with every suggestion reviewed, because a hallucinated method on a standard object compiles in the assistant's imagination and not in your org.\n\nAgentforce is covered from the developer side: agent actions backed by Apex, grounding on org data, and the integration work that feeds an agent something worth reasoning over. The career guide's caveat applies here too — this sits on top of platform fundamentals, not instead of them.",
      topics: [
        "AI assistants for Apex and LWC scaffolding",
        "Generating test classes and improving coverage",
        "Explaining and refactoring inherited Apex",
        "Spotting hallucinated methods and objects",
        "Documentation and code-comment generation",
        "Agentforce agent actions backed by Apex",
        "Grounding an agent on org data",
        "Integration as the input to useful AI",
        "Data privacy when using external AI tools",
        "A mini-project built with an AI-assisted workflow",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-developer-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Eleven-stage Salesforce Developer learning path taught at Archer Infotech Pune: platform foundations covering objects, security and developer tooling; Apex fundamentals covering data types, collections, classes and DML; SOQL and SOSL covering relationship queries and selectivity; triggers, bulkification and governor limits; asynchronous Apex covering future, Queueable, Batch and Scheduled; Lightning Web Components covering templates, reactivity, events and wire adapters; integration covering REST, SOAP, callouts, named credentials and OAuth; testing, debugging and code quality; deployment with Salesforce DX and DevOps; a capstone build with Platform Developer I preparation; and AI-assisted development with Agentforce.",
    caption:
      "The order this course is taught in — the platform before the language, and governor limits before anything is built on them. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-developer-syllabus-v1.pdf",
    title: "Salesforce Developer Syllabus — Complete Module List",
    slug: "salesforce-developer-syllabus",
    blurb:
      "All twelve modules as a PDF — platform foundations for developers, Apex, SOQL and SOSL, triggers and governor limits, asynchronous Apex, Lightning Web Components, integration and platform APIs, testing and debugging, Salesforce DX and DevOps, the capstone build with Platform Developer I preparation, and AI-assisted development. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All twelve modules in teaching order, each with its schedule, description and full topic list.",
          "Governor limits and bulkification given their own module early, rather than appearing as a warning after the code is already written badly.",
          "Integration in depth — REST, SOAP, Bulk and Composite APIs, named credentials, OAuth flows and the JWT bearer flow — because that is where the salary premium sits.",
          "Salesforce DX, scratch orgs, unlocked packages, Git branching and CI validation, which most Salesforce courses stop short of entirely.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Developer — the role this course is written for.",
          "Salesforce Platform Developer at services majors and consulting partners.",
          "Salesforce Integration Developer, with the API and middleware depth added.",
          "The engineering grounding assumed by the Technical Architect path.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Full Application Build with Triggers, Async and LWC",
      description:
        "A complete application in your own org: a custom data model, a trigger handler framework, Batch and Queueable processing over a realistic data volume, a Lightning Web Component front end with events and wire adapters, and a test suite with meaningful assertions rather than coverage padding. Deployed through a Salesforce DX pipeline you configured yourself.",
      technologies: [
        "Apex triggers and handler framework",
        "Batch and Queueable Apex",
        "Lightning Web Components",
        "Jest and Apex tests",
        "Salesforce DX and Git",
        "Your own Developer Edition org",
      ],
    },
    {
      title: "Two-Way Integration with an External System",
      description:
        "Integrate your org with an external REST service in both directions — outbound callouts from Apex using named credentials with retry and idempotency handling, and an inbound Apex REST endpoint secured through a connected app and OAuth. Includes error logging, replay handling and a written note on why the chosen API suits the volume. The single most interview-relevant artefact a Salesforce developer can carry.",
      technologies: [
        "Apex REST and HTTP callouts",
        "Named and external credentials",
        "OAuth and connected apps",
        "Platform events",
        "Error logging and retry design",
      ],
    },
  ],

  trainersIntro:
    "Salesforce development sessions are led by a trainer who ships Apex and Lightning Web Components on a production org rather than only teaching them. Code is reviewed in your own org and against your own repository, not assessed from screenshots.",

  careerOutcomes: {
    paragraphs: [
      "Salesforce development hiring in Pune runs across services majors with dedicated practices, Salesforce-native consulting partners and the captive centres of global enterprises. Postings appear as Salesforce Developer, Salesforce Platform Developer, Apex Developer and increasingly as integration-focused roles, which are the hardest for employers to fill and correspondingly the best paid.",
      "What moves a developer up the band, in the order it actually matters: Apex and LWC competence, then integration and API design, then DevOps and release engineering, then architecture. Our career guide names the same set. A certification opens the screen; the code you can walk someone through, and the integration you can explain the failure modes of, decide the round.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Developer",
      "Salesforce Platform Developer",
      "Apex Developer",
      "Salesforce Integration Developer",
      "Salesforce Full Stack Developer",
      "Junior Salesforce Technical Consultant",
    ],
  },

  modesAndDuration: {
    duration: "3.5 months (14 weeks) for the weekday and online tracks; 16 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "VS Code with Salesforce Extensions (free)",
        "Salesforce CLI and scratch orgs (free)",
        "GitHub for code review",
        "Postman for API work",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 16 weeks rather than 14 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Developer sits in the upper-mid band of our catalogue, reflecting a three-and-a-half-month duration and the trainer demand this track carries. The Salesforce Platform Developer I examination fee is paid by you directly to Salesforce when you choose to sit, and is never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹40,000 – ₹55,000 (typical band) plus the Salesforce examination fee, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week ten rather than after you finish. By graduation your resume is rewritten for developer job descriptions, your capstone repository is reviewed, and you have completed at least two mock technical interviews covering Apex, governor limits, LWC and integration.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 10 — resume and LinkedIn rewritten for developer roles",
      "Week 11 — GitHub repository and capstone architecture reviewed",
      "Week 12 — first mock interview on Apex, triggers and governor limits",
      "Week 13 — second mock interview on LWC and integration scenarios",
      "Week 14 — certification-readiness check for Platform Developer I",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins and cert-prep coaching",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Salesforce Developer or a general Java or full-stack role?",
    paragraphs: [
      "If you can already program, the comparison worth making is not Apex against Java but ecosystem against ecosystem. General Java and full-stack roles are far more numerous in Pune and the skills transfer anywhere. Salesforce roles are fewer, pay better at the same experience for integration-capable developers, and the skills are deep inside one platform rather than portable outside it.",
      "The Salesforce advantage is a clearer ladder and less competition per posting. The Salesforce disadvantage is exactly the platform specialisation our career guide is candid about — five years of Apex is worth a great deal inside the ecosystem and considerably less outside it, which is a trade worth making knowingly rather than by accident.",
      "The pragmatic route many Pune developers take: keep general programming current, add Salesforce as the specialisation, and let integration work be the bridge. Integration developers are the hardest Salesforce role to fill and the one whose skills travel best.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "You need to be able to program before this course, in any object-oriented language — Java, C#, Python or JavaScript are all fine starting points, and Java transfers most directly because Apex borrowed its syntax. You do not need prior Salesforce experience; week one covers the administrator layer a developer cannot skip. What does not work is arriving without programming: Apex is a real language with real constraints, and this course teaches the platform rather than teaching you to code.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to confirm the developer path fits your background",
      "Create a free Developer Edition org and complete a Trailhead Apex basics module",
      "Check the upcoming batch dates and pick a mode — classroom, live online or weekend",
      "Book a free counselling session, especially if you are unsure between this and the Administrator path",
      "Enrol, and arrive at session one with a laptop — VS Code and CLI setup happens on day one",
    ],
  },

  faqs: [
    {
      question: "Do I need to know Java before learning Apex?",
      answer:
        "Not Java specifically, but you do need to be able to program in some object-oriented language. Apex borrowed Java's syntax and object model, which is why our career guide notes Java developers transition fastest — but C#, Python and JavaScript developers manage the move perfectly well. What does not work is arriving with no programming at all; take the Salesforce Administrator path first in that case.",
    },
    {
      question: "Do I need to learn Salesforce Administration before Development?",
      answer:
        "You need the administrator layer, and week one covers it — objects, relationships, record types, profiles, permission sets and sharing. You do not need the full Administrator course, but you cannot skip the concepts. Apex runs inside the security and data model an administrator owns, and code written without understanding it either fails or leaks data quietly, which is worse.",
    },
    {
      question: "What are governor limits and why does everyone mention them?",
      answer:
        "Salesforce is multi-tenant — your code shares infrastructure with every other customer — so the platform caps how much any single transaction may consume: queries, DML statements, CPU time, heap and callouts. Code that ignores them passes in a small org and fails on real data. This course gives them their own module in week five rather than mentioning them after you have already built things badly.",
    },
    {
      question: "Which certification should I take, and when?",
      answer:
        "Platform Developer I is the one this course aligns to, and it is what Pune employers screen developer candidates on. Sit it within four to six weeks of finishing, while the material is current. Administrator is worth adding if you came in without configuration background. Platform Developer II is a later credential that assumes real project experience — it is not a fresher target.",
    },
    {
      question: "Will I learn integration, or only Apex and LWC?",
      answer:
        "Integration gets a full module covering both directions: Salesforce as an API provider through REST, SOAP, Bulk and Composite APIs, and as a consumer through Apex callouts, named credentials and OAuth. It is included deliberately because integration-capable developers are the hardest Salesforce role for Pune employers to fill and the best paid at the same experience.",
    },
    {
      question: "Is Lightning Web Components hard if I know React?",
      answer:
        "It will feel familiar and occasionally frustrating. LWC uses web standards — custom elements, shadow DOM, modules — so component thinking, props and events all transfer. What differs is the platform integration: wire adapters, Lightning Data Service and the metadata that decides where a component can be placed. A React developer typically reaches productive LWC within two weeks.",
    },
    {
      question: "Do I get my own org and can I keep it?",
      answer:
        "Yes to both. You work in a free Developer Edition org from week one and keep it afterwards, along with your capstone code in your own GitHub repository. Practising in a shared trainer demo org is a poor substitute — you cannot deploy, you cannot break anything meaningful, and you leave with nothing to show an interviewer.",
    },
    {
      question: "How much does a Salesforce Developer earn in Pune?",
      answer:
        "The indicative India-wide bands from our career guide are ₹3–6 LPA at entry, ₹6–12 LPA at one to three years and ₹10–20 LPA at three to five, with integration and architecture depth pushing toward the upper end. These are market ranges, not promises — Pune services majors typically land lower in each band and Salesforce-native partners somewhat higher for the same experience.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your org and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Developer training in Pune?",
    paragraph:
      "Three and a half months from now you can have a deployed application in your own org, a two-way integration you built and can explain the failure modes of, a repository an interviewer can open, and a clear run at the Platform Developer I exam. Bring a programming background; we will teach you the platform. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
