import type { CourseRichContent } from "./types";

/**
 * Salesforce Administrator — rich content overlay.
 *
 * Path 1 of the eight in the Salesforce Career Guide 2026. The entry path
 * that genuinely does not require programming, aimed at the non-IT
 * graduates the guide names. Kept deliberately distinct from the combined
 * Admin + Developer track, which teaches Apex as well.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceAdministratorTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Administrator is the most accessible entry into the Salesforce ecosystem, and the only one of the eight career paths where programming is genuinely not required. An administrator owns the org: users and permissions, the security model, objects and fields, data quality, reports and dashboards, and the automation that runs the business without a line of code. This three-month programme is taught entirely in your own Salesforce org, aligned to the Salesforce Certified Administrator exam, and finishes with a configured application you can demonstrate at interview. Classroom in Kothrud, live online and weekend batches.",

  whyLearn: {
    heading: "Why Learn Salesforce Administration in Pune in 2026",
    paragraphs: [
      "Salesforce administration is one of very few well-paid technology careers that a BCom, BBA or MBA graduate can enter without first learning to program. The work is configuration and judgement rather than code: deciding how a business process should be modelled, who should see what, and which automation is worth building. That makes it the path our career guide points non-IT graduates and career switchers toward first.",
      "Pune's demand comes from the services majors with dedicated Salesforce practices — Cognizant, Accenture, TCS, Capgemini, LTIMindtree, Persistent — and from the Salesforce-native consulting partners who tend to pay somewhat more for the same experience. Both need administrators, and both screen on the same two things: the Salesforce Certified Administrator credential, and evidence that you have configured a real org rather than watched someone configure one.",
      "The honest framing is that administration is a starting point rather than a destination. Most Pune administrators move within two to three years into a consultant, business analyst or developer track, and the administrator grounding is what makes those moves possible — a developer who does not understand the security model writes Apex that quietly breaks it. Treat this course as the foundation the other seven paths are built on.",
    ],
    keyPoints: [
      "The one Salesforce path where programming is genuinely not required",
      "Accessible to BCom, BBA, MBA and non-IT graduates",
      "Aligned to the Salesforce Certified Administrator exam",
      "Taught entirely in your own org, which you keep",
      "The grounding every other Salesforce path assumes",
      "Indicative fresher band ₹3–6 LPA, rising with certification and project work",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "BCom, BBA, MBA and other non-IT graduates entering the technology industry",
      "Career switchers from operations, support, sales operations or customer service",
      "Business analysts and project coordinators adding a platform skill",
      "CRM users who already work inside Salesforce and want to administer it",
      "Working professionals who want a technology career without a coding-first path",
      "Anyone intending to move later into consultant, business analyst or developer work",
    ],
    notForYou: [
      "Anyone specifically wanting to write code — take the Salesforce Developer path instead",
      "Candidates expecting the institute to issue a Salesforce certification; only Salesforce can do that",
      "Learners unwilling to spend time in an org between sessions, since configuration is a practical skill",
      "Anyone treating administration as a final destination rather than a first step",
    ],
  },

  curriculum: [
    {
      title: "CRM Concepts & the Salesforce Platform",
      weekRange: "Week 1",
      description:
        "What a CRM is for before what Salesforce does, because an administrator who does not understand the business problem configures the wrong solution competently. Leads, accounts, contacts, opportunities and cases as business concepts, then as platform objects.\n\nYou set up your own Developer Edition org in the first session and keep it for the rest of the course and afterwards. Editions, licences, the Setup menu, Lightning Experience navigation and the app launcher follow, along with Trailhead — used alongside the teaching with a set sequence, not handed over instead of it.",
      topics: [
        "What a CRM is for, in business terms",
        "Salesforce clouds and what each covers",
        "Editions, licences and org types",
        "Creating and keeping your own Developer org",
        "Lightning Experience navigation and the app launcher",
        "The Setup menu and where things live",
        "Standard objects — leads, accounts, contacts, opportunities, cases",
        "Trailhead, trailmixes and superbadges",
        "Release cycles and staying current",
      ],
    },
    {
      title: "Users, Profiles, Roles & Permission Sets",
      weekRange: "Week 2",
      description:
        "The security model, which is the administrator's core responsibility and the part interviews probe hardest. User setup and licences; profiles as the baseline of what a user can do; permission sets and permission set groups as the additive layer that modern Salesforce prefers to profile proliferation.\n\nRoles are covered separately from profiles because conflating the two is the single most common beginner error: a profile decides what you can do, a role decides whose records you can see. You build a working model for a fictional organisation and then test it by logging in as each user.",
      topics: [
        "Creating users, licences and user management",
        "Profiles and what they control",
        "Permission sets and permission set groups",
        "Profiles versus permission sets in modern practice",
        "The role hierarchy and record visibility",
        "Public groups and queues",
        "Login history, password policies and session settings",
        "Multi-factor authentication requirements",
        "Login As and testing a security model",
      ],
    },
    {
      title: "The Security Model — Sharing, OWD & Field-Level Security",
      weekRange: "Week 3",
      description:
        "Record-level access in depth. Organisation-wide defaults as the floor, then the mechanisms that open access back up: role hierarchy, sharing rules, manual sharing and team access. The order matters and the exam tests it, so you work through scenarios and predict the outcome before checking.\n\nField-level security and page layouts control what a user sees on a record they can already access — a distinction candidates routinely blur. The module closes on restriction rules, and on the practical discipline of documenting a sharing model so the next administrator can understand it.",
      topics: [
        "Organisation-wide defaults",
        "Role hierarchy and record access inheritance",
        "Ownership-based and criteria-based sharing rules",
        "Manual sharing and account teams",
        "Field-level security versus page layout visibility",
        "Restriction rules and scoping rules",
        "Predicting effective access in a scenario",
        "Auditing and documenting a sharing model",
        "Common security misconfigurations",
      ],
    },
    {
      title: "Objects, Fields & Relationships",
      weekRange: "Week 4",
      description:
        "Data modelling, which is where an administrator's decisions have the longest consequences. Standard against custom objects; field types and the ones that cannot be changed later; and relationships — lookup, master-detail, hierarchical and many-to-many through a junction object.\n\nThe master-detail versus lookup decision gets extended treatment because it determines cascade delete, roll-up summaries and record ownership, and it is difficult to reverse once records exist. You model a real business scenario end to end and defend the choices.",
      topics: [
        "Standard and custom objects",
        "Field types and choosing correctly",
        "Formula fields and roll-up summaries",
        "Lookup versus master-detail relationships",
        "Junction objects and many-to-many",
        "Hierarchical relationships",
        "Schema Builder and the object manager",
        "Record types and page layout assignment",
        "Modelling a business scenario from requirements",
      ],
    },
    {
      title: "Page Layouts, Lightning Pages & the User Interface",
      weekRange: "Week 5",
      description:
        "What the user actually sees, and the difference between an org people use and one they work around. Page layouts, compact layouts and record types; the Lightning App Builder for dynamic record pages; and dynamic forms, which increasingly replace layout proliferation.\n\nList views, filters, kanban and the search behaviour users rely on. The judgement taught here is restraint: every field you add to a layout costs attention, and an administrator's job includes saying no to requests that would clutter the page for everyone.",
      topics: [
        "Page layouts, compact layouts and related lists",
        "Record types and layout assignment",
        "Lightning App Builder and record pages",
        "Dynamic forms and dynamic actions",
        "Custom apps, tabs and navigation",
        "List views, filters and kanban",
        "Global search and search layouts",
        "Home page and utility bar configuration",
        "Designing for the user, not the requester",
      ],
    },
    {
      title: "Validation Rules & Data Quality",
      weekRange: "Week 6",
      description:
        "Keeping the data worth reporting on, which is the quiet half of the job. Validation rules with the formula syntax they use, required fields, duplicate rules and matching rules, and the trade-off every rule carries: each one prevents bad data and adds friction for a user who then finds a way around it.\n\nData management covers imports with the Data Import Wizard and Data Loader, external IDs and upsert, mass updates and deletion, and the recycle bin. You clean a deliberately messy dataset, which is closer to the real job than any greenfield exercise.",
      topics: [
        "Validation rules and formula syntax",
        "Required fields, dependent picklists and defaults",
        "Duplicate rules and matching rules",
        "Data Import Wizard versus Data Loader",
        "External IDs and upsert operations",
        "Mass update, transfer and delete",
        "Recycle bin and data recovery",
        "Data quality auditing",
        "Balancing enforcement against usability",
      ],
    },
    {
      title: "Flow Builder & Declarative Automation",
      weekRange: "Weeks 7–8",
      description:
        "The automation engine, and the skill that most separates a capable administrator from someone who can only configure fields. Flow types — screen, record-triggered, scheduled, autolaunched and platform-event-triggered — and what each is for.\n\nYou build flows with variables, collections, loops, decisions, assignments and get, create and update elements; add fault paths, because a flow without one fails silently in production; and cover before-save against after-save triggers and the performance difference. Approval processes and the legacy Workflow and Process Builder are covered for the orgs you will inherit that still use them.",
      topics: [
        "Flow types and choosing between them",
        "Screen flows and guided user experiences",
        "Record-triggered flows, before and after save",
        "Variables, collections, loops and decisions",
        "Get, create, update and delete elements",
        "Fault paths and error handling",
        "Scheduled and platform-event flows",
        "Subflows and reusable logic",
        "Approval processes",
        "Legacy Workflow and Process Builder in inherited orgs",
        "Debugging a flow and reading the debug log",
      ],
    },
    {
      title: "Reports & Dashboards",
      weekRange: "Week 9",
      description:
        "Turning the data into the answers a manager actually asks for. Report types and why a custom report type is often the missing piece; tabular, summary, matrix and joined formats; filters, cross filters, bucketing and row-level formulas.\n\nDashboards cover component types, dynamic dashboards, filters, and running-user context — which is where dashboards quietly leak data if the running user is set carelessly. The module closes on the skill that matters most: starting from the question being asked rather than from the report builder.",
      topics: [
        "Report types and custom report types",
        "Tabular, summary, matrix and joined reports",
        "Filters, cross filters and filter logic",
        "Bucketing, groupings and summary formulas",
        "Row-level formulas",
        "Charts and conditional formatting",
        "Dashboard components and layout",
        "Dynamic dashboards and running user",
        "Subscriptions and scheduled reports",
        "Starting from the question, not the builder",
      ],
    },
    {
      title: "Sales & Service Cloud for Administrators",
      weekRange: "Week 10",
      description:
        "The two clouds an administrator is most often asked to configure. Sales Cloud covers the lead-to-cash process: lead conversion, opportunity stages and sales path, products and price books, quotes, forecasting and campaign influence.\n\nService Cloud covers case management: case creation channels, assignment and escalation rules, queues, entitlements and milestones, knowledge articles, and the omni-channel routing basics. Both are taught as configuration decisions driven by a business process rather than as feature tours.",
      topics: [
        "Lead management, conversion and assignment rules",
        "Opportunity stages, sales path and forecasting",
        "Products, price books and quotes",
        "Campaigns and campaign influence",
        "Case creation channels — email, web, phone",
        "Assignment rules, escalation rules and queues",
        "Entitlements, milestones and service contracts",
        "Knowledge articles and case deflection",
        "Omni-channel routing basics",
        "Configuring from a documented process",
      ],
    },
    {
      title: "AppExchange, Sandboxes & Change Management",
      weekRange: "Week 11",
      description:
        "Working in an org other people depend on. Sandboxes and their types, what refreshes and what does not, and the discipline of building somewhere other than production — which every administrator learns either in a course or through an incident.\n\nDeployment covers change sets, packages and an introduction to Salesforce DX, plus the AppExchange evaluation questions worth asking before installing anything: what permissions it wants, what happens when it is uninstalled, and who supports it. Release management and the three annual Salesforce releases close the module.",
      topics: [
        "Sandbox types and refresh behaviour",
        "Building outside production",
        "Change sets and deployment",
        "Packages and an introduction to Salesforce DX",
        "AppExchange evaluation and permissions",
        "Managed versus unmanaged packages",
        "The three annual releases and preview orgs",
        "Release notes and impact assessment",
        "Documenting configuration for the next administrator",
      ],
    },
    {
      title: "Certification Preparation & Exam Strategy",
      weekRange: "Week 12 + placement prep",
      description:
        "Structured preparation for the Salesforce Certified Administrator exam, which is the credential Pune employers screen on. The exam's sections and their weightings, the question style — scenario-based rather than recall — and the pacing that gets you through the paper with time to review flagged items.\n\nYou sit timed mock papers, work through the questions you got wrong rather than the ones you got right, and close the gaps that shows up. Booking, proctoring and the maintenance requirement are covered plainly, along with the standing point that the exam fee is paid to Salesforce, never to us.",
      topics: [
        "Exam sections and their weightings",
        "Scenario question style and how to read one",
        "Timed mock papers and pacing",
        "Working through wrong answers systematically",
        "Booking, proctoring and identification",
        "The maintenance requirement each release",
        "Trailhead superbadges as evidence",
        "Building an interview-ready org walkthrough",
        "Resume and LinkedIn for administrator roles",
        "Mock interviews on configuration scenarios",
      ],
    },
    {
      title: "AI-Assisted Administration & Agentforce Awareness",
      weekRange: "Final Week",
      description:
        "Where AI sits for an administrator in 2026, framed the way our career guide frames it: on top of fundamentals, not instead of them. Einstein features an administrator configures, Prompt Builder, and an orientation to Agentforce — agents, actions and grounding — at the level of understanding what is being asked for when it appears in a requirement.\n\nThe standing caveat is repeated because it matters: a fresher who learns Agentforce without understanding the object model and Flow will not clear an interview. The rest of the module covers using AI assistants responsibly for formula writing, documentation and release-note triage, with every suggestion reviewed before it reaches an org.",
      topics: [
        "Einstein features an administrator configures",
        "Prompt Builder and prompt templates",
        "Agentforce — agents, actions and grounding",
        "Why AI sits on top of the object model and Flow",
        "Data quality as the prerequisite for useful AI",
        "AI assistants for formula and validation-rule drafting",
        "Generating documentation and release-note summaries",
        "Reviewing every AI suggestion before it reaches an org",
        "Data privacy when using external AI tools",
        "A small AI-assisted configuration task, end to end",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-admin-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Eight-stage Salesforce Administrator learning path taught at Archer Infotech Pune: platform basics covering CRM concepts, objects and the data model; users and access covering profiles, permission sets and the role hierarchy; the security model covering organisation-wide defaults, sharing rules and field-level security; data modelling covering objects, fields and relationships; user interface covering page layouts, Lightning pages and list views; automation covering Flow Builder, validation rules and approval processes; reports and dashboards; and certification preparation with mock exams and exam strategy.",
    caption:
      "The order this course is taught in — configuration before automation, automation before reporting. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-administrator-syllabus-v1.pdf",
    title: "Salesforce Administrator Syllabus — Complete Module List",
    slug: "salesforce-administrator-syllabus",
    blurb:
      "All twelve modules as a PDF — CRM and platform basics, the full security model, data modelling, user interface configuration, validation and data quality, Flow Builder, reports and dashboards, Sales and Service Cloud configuration, sandboxes and change management, certification preparation and AI-assisted administration. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All twelve modules in teaching order, each with its schedule, description and full topic list.",
          "The security model across two modules — profiles, permission sets, role hierarchy, organisation-wide defaults, sharing rules and field-level security — because it is where administrator interviews concentrate.",
          "Flow Builder given two weeks, including fault paths, before-save versus after-save, and the legacy Workflow and Process Builder you will meet in inherited orgs.",
          "Certification preparation with exam weightings, question style, pacing and the maintenance requirement — plus the plain statement that the exam fee is paid to Salesforce, not to us.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Administrator — the role this course is written for.",
          "Junior Salesforce Consultant, once configuration depth is established.",
          "Salesforce Business Analyst, with requirements and process work added.",
          "The grounding assumed by the Developer, Consultant and Architect paths.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Configured Org for a Real Business Process",
      description:
        "Take a documented business process — a recruitment pipeline, a service desk, a membership organisation — and build it end to end in your own org: custom objects and relationships, record types, page layouts, a security model with organisation-wide defaults and sharing rules, validation rules, record-triggered and screen flows, and a reporting pack. Documented as a configuration workbook a second administrator could follow, which is the artefact interviewers respond to.",
      technologies: [
        "Custom objects and relationships",
        "Profiles, permission sets, sharing rules",
        "Flow Builder",
        "Validation rules",
        "Reports and dashboards",
        "Your own Developer Edition org",
      ],
    },
    {
      title: "Data Quality and Migration Exercise",
      description:
        "Import a deliberately messy dataset — duplicates, inconsistent picklist values, broken relationships, missing required fields — using Data Loader and external IDs, then build the duplicate rules, validation rules and reports that stop it degrading again. The exercise closest to the first month of an actual administrator job.",
      technologies: [
        "Data Loader and external IDs",
        "Duplicate and matching rules",
        "Validation rules",
        "Data quality reports",
        "Mass update and transfer",
      ],
    },
  ],

  trainersIntro:
    "Salesforce sessions are led by a trainer who administers a production org day to day rather than only teaching the subject. Configuration is reviewed in your own org, not assessed from screenshots.",

  careerOutcomes: {
    paragraphs: [
      "Salesforce administration is the entry point our career guide names for non-IT graduates, and Pune has consistent demand across services majors with Salesforce practices, Salesforce-native consulting partners, and the captive centres of global enterprises. Postings appear as Salesforce Administrator, Salesforce Support Analyst and increasingly as combined administrator-and-analyst roles.",
      "What moves an administrator up is not another certification but depth: configuration judgement, Flow fluency, requirements gathering, business process knowledge, and the communication to say no to a request that would damage the org. Certification opens the screen; the org you can walk someone through decides the round.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Administrator",
      "Salesforce Support Analyst",
      "Junior Salesforce Consultant",
      "Salesforce Business Analyst (with requirements work added)",
      "CRM Analyst",
      "Salesforce Operations Specialist",
    ],
  },

  modesAndDuration: {
    duration: "3 months (12 weeks) for the weekday and online tracks; 14 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "Trailhead and trailmixes (free)",
        "Data Loader (free)",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 14 weeks rather than 12 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Administrator sits in the mid band of our catalogue, reflecting a three-month duration. The Salesforce Certified Administrator examination fee is paid by you directly to Salesforce when you choose to sit, and is never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹30,000 – ₹45,000 (typical band) plus the Salesforce examination fee, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week nine rather than after you finish. By graduation your resume is rewritten for administrator job descriptions, your org walkthrough is rehearsed, and you have completed at least two mock interviews on configuration scenarios.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 9 — resume and LinkedIn rewritten for administrator roles",
      "Week 10 — org walkthrough rehearsed and reviewed by the trainer",
      "Week 11 — first mock interview on configuration and security scenarios",
      "Week 12 — certification-readiness check and second mock interview",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins and cert-prep coaching",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Administrator or the combined Admin + Developer track?",
    paragraphs: [
      "Take this course if you do not want to write code, or not yet. It covers administration to interview depth and stops there, which is the right scope for a BCom, BBA or MBA graduate entering the ecosystem and for anyone moving across from operations or support.",
      "Take the combined Admin + Developer track if you already program, or intend to. Apex is Java-like, which is why our career guide notes Java developers transition fastest, and a combined profile is what a large share of Pune postings ask for by name.",
      "The honest note: you are not choosing permanently. Most administrators add development or consulting skills within two to three years, and this course is the grounding both of those build on. What does not work is the reverse — attempting Apex without understanding the security model and object relationships produces code that breaks things quietly.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "No programming and no IT background is required. What is required is comfort with a computer, willingness to spend time in your own org between sessions, and the patience to read a requirement carefully before configuring anything. Graduates from any discipline join this course; the strongest performers are frequently the ones who have worked in a business process rather than a technical one, because they already know what the software has to support.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to confirm the administrator path fits your background",
      "Create a free Salesforce Developer Edition org and click through it for an hour",
      "Check the upcoming batch dates and pick a mode — classroom, live online or weekend",
      "Book a free counselling session to confirm this rather than the combined track",
      "Enrol, and bring a laptop to session one — org setup happens on day one",
    ],
  },

  faqs: [
    {
      question: "Do I need programming knowledge to become a Salesforce Administrator?",
      answer:
        "No, and this is the one Salesforce career path where that is genuinely true rather than a marketing line. Administration is configuration and judgement — the security model, data model, page layouts, validation rules, Flow automation and reporting — all done through the interface. Formula syntax appears in validation rules and formula fields, which is closer to spreadsheet formulas than to programming. If you want to write Apex, take the Developer path instead.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. The Salesforce Certified Administrator exam is booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you, which is exactly the confusion our career guide warns about.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. This distinction costs students money every year, so ask it plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "How long does it take to become job-ready as an administrator?",
      answer:
        "Three months of course plus the certification, which most learners sit within four to six weeks of finishing. The variable is practice: an hour in your own org between sessions is worth more than any amount of watching. Graduates who postpone the exam beyond six weeks place noticeably slower, which is why the certification-readiness checks are built into the placement process.",
    },
    {
      question: "What is the difference between a profile and a role?",
      answer:
        "A profile decides what a user can do — which objects and fields they can access, and which permissions they hold. A role decides whose records they can see, through the role hierarchy. Conflating them is the most common beginner error and a reliable interview question. Modern practice keeps profiles minimal and grants additional access through permission sets and permission set groups.",
    },
    {
      question: "Will I get my own Salesforce org to practise in?",
      answer:
        "Yes, from the first session, and you keep it after the course ends. A free Developer Edition org has effectively the full platform in it, which is why practising in a shared trainer demo org is a poor substitute — you cannot break anything meaningful, and breaking things and fixing them is how administration is learned.",
    },
    {
      question: "Do I need to learn Flow, or is Workflow still enough?",
      answer:
        "Flow, without question. Salesforce has retired Workflow Rules and Process Builder for new automation, and Flow Builder is now the single declarative automation tool. Legacy Workflow and Process Builder are covered here because you will inherit orgs that still run them and will be asked to migrate them, but everything new you build will be a Flow.",
    },
    {
      question: "What comes after the Administrator course?",
      answer:
        "Depending on what you enjoyed: the Business Analyst path if you liked the requirements and process side, the Developer path if you want to write Apex and Lightning Web Components, or the Consultant path once you have a couple of years of implementation experience. Our career guide sets out all eight paths and which background each suits — administration is the grounding under most of them.",
    },
    {
      question: "Can a non-IT graduate really get a Salesforce job in Pune?",
      answer:
        "Yes, and it is one of the few technology entries where that is routinely true. Pune's services majors and Salesforce consulting partners hire administrators from commerce, management and arts backgrounds. What they screen on is the Salesforce certification and evidence of real configuration work — not your degree subject. Communication matters more here than in most technical roles, because an administrator spends a great deal of time talking to the business.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over 14 weeks, and live online runs weekday evenings over 12, both with the same content, the same trainer review of your org and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting for administrator job descriptions, rehearsing your org walkthrough, two mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
    {
      question: "Should I learn Agentforce and AI features as a beginner?",
      answer:
        "Learn them, but after the fundamentals rather than instead of them. The final week covers Einstein features, Prompt Builder and an orientation to Agentforce, and the position we take is the one in our career guide: a fresher who learns Agentforce without understanding the object model and Flow will not clear an interview. AI sits on top of strong platform knowledge and amplifies it; it does not substitute for it.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Administrator training in Pune?",
    paragraph:
      "Three months from now you can have a configured org you built yourself, a documented project you can walk an interviewer through, mock interviews behind you, and a clear run at the Salesforce Certified Administrator exam. No programming background is needed to start. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
