import type { CourseRichContent } from "./types";

/**
 * Salesforce Data & Analytics — rich content overlay.
 *
 * Path 5 of the eight in the Salesforce Career Guide 2026. Data modelling,
 * quality, reporting, Data Cloud, Tableau and integration — aimed at the
 * data analysts, BI professionals and experienced Salesforce people the
 * guide names.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceDataAnalyticsTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Data & Analytics is the path for people who care about what the data says rather than how the screen looks. It covers data modelling and quality, reporting and dashboards to real analytical depth, CRM Analytics, Data Cloud for unifying customer data across systems, Tableau, and the integration and migration work that feeds all of it. Three months, taught in your own org against realistic messy data, finishing with an analytics build you can demonstrate. Suited to data analysts, BI professionals and Salesforce administrators moving deeper.",

  whyLearn: {
    heading: "Why Learn Salesforce Data & Analytics in Pune in 2026",
    paragraphs: [
      "Every Salesforce org accumulates data faster than anyone maintains it, and the gap between having data and being able to answer a question with it is where this role lives. Pune's services majors and consulting partners both staff data-focused Salesforce people on larger deliveries, and the demand has grown sharply as Data Cloud and Agentforce have made data quality a blocking dependency rather than a background concern.",
      "The path suits two populations well. Data analysts and BI professionals already have the analytical craft and need the platform: the object model, reporting constraints and how Salesforce data actually behaves. Salesforce administrators already have the platform and need the analytical depth. Either direction is a shorter move than starting from nothing, which is why our career guide names both.",
      "The strategic argument is Agentforce. Salesforce has moved decisively toward an agent-first platform, and an agent grounded on bad data is worse than no agent. That has turned data quality, unification and governance from unglamorous maintenance into the thing everything else now depends on — and it is the reason this specialisation has become considerably more valuable than it was two years ago.",
    ],
    keyPoints: [
      "Suits data analysts and BI professionals moving into the ecosystem",
      "Equally suits Salesforce administrators wanting analytical depth",
      "Covers CRM Analytics, Data Cloud and Tableau, not just standard reports",
      "Data quality is now the blocking dependency for Agentforce and AI",
      "Taught against realistic messy data rather than clean sample sets",
      "Indicative 3–5 year band ₹10–20 LPA",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "Data analysts and BI professionals moving into the Salesforce ecosystem",
      "Salesforce administrators who want analytical and data depth",
      "Reporting and MIS professionals in organisations running Salesforce",
      "Data engineers working on customer data platforms",
      "Anyone whose interest is in what the data says rather than what the interface does",
    ],
    notForYou: [
      "Complete beginners with neither data nor Salesforce background — start with Administrator",
      "Anyone wanting to build application features; the Developer path fits better",
      "Learners looking for a purely business-facing role, since this one is genuinely technical",
    ],
  },

  curriculum: [
    {
      title: "Salesforce Data Model & Platform Foundations",
      weekRange: "Week 1",
      description:
        "The platform from a data perspective. Objects, fields and relationships as a schema; standard object relationships in Sales and Service Cloud; record types and how they complicate reporting; and the security model, because record visibility silently changes every number a report produces.\n\nYou set up your own org and load a deliberately imperfect dataset that the rest of the course works against.",
      topics: [
        "Objects, fields and relationships as a schema",
        "Standard Sales and Service Cloud data relationships",
        "Record types and their reporting consequences",
        "Sharing, visibility and how they change report totals",
        "Data types, precision and formula fields",
        "Setting up your own org and loading real data",
        "Schema Builder and documenting a model",
        "Where Salesforce data differs from a warehouse",
      ],
    },
    {
      title: "Data Quality, Governance & Stewardship",
      weekRange: "Week 2",
      description:
        "The unglamorous foundation everything else rests on. Profiling a dataset to find what is actually wrong with it; duplicate and matching rules; validation and picklist governance; and the ownership question — who is accountable for a field being correct.\n\nThe discipline taught is measurement: a data quality dashboard that reports completeness, validity and duplication over time turns an opinion into a metric someone can be held to.",
      topics: [
        "Profiling a dataset and finding what is wrong",
        "Duplicate rules, matching rules and merge strategy",
        "Validation rules and picklist governance",
        "Required-field policy and its cost",
        "Data ownership and stewardship",
        "Completeness, validity and consistency metrics",
        "Building a data quality dashboard",
        "Remediation planning and prioritisation",
      ],
    },
    {
      title: "Reports & Dashboards to Analytical Depth",
      weekRange: "Weeks 3–4",
      description:
        "Standard reporting taken well past where most administrators stop. Custom report types, which are usually the missing piece when a report cannot be built; joined reports; cross filters; bucketing; row-level formulas; and summary formulas with the PARENTGROUPVAL functions people rarely reach for.\n\nDashboards cover dynamic dashboards, running-user context and its data-leak risk, filters and subscriptions. The framing throughout is starting from the question rather than the builder.",
      topics: [
        "Custom report types and why reports fail without them",
        "Joined reports and multiple blocks",
        "Cross filters and filter logic",
        "Bucketing and row-level formulas",
        "Summary formulas and PARENTGROUPVAL",
        "Dynamic dashboards and running user",
        "Running-user context as a data-leak risk",
        "Subscriptions, scheduling and delivery",
        "Starting from the question, not the builder",
      ],
    },
    {
      title: "Data Migration, Loading & Integration",
      weekRange: "Week 5",
      description:
        "Getting data in and out reliably. Data Loader and the Bulk API for volume; external IDs and upsert; sequencing loads so relationships resolve; and the reconciliation step that proves a migration actually worked rather than merely finished.\n\nIntegration covers the patterns that feed analytics: scheduled extracts, event-driven updates, Change Data Capture, and external objects with Salesforce Connect for data that should not be copied at all.",
      topics: [
        "Data Loader, Bulk API and volume handling",
        "External IDs and upsert semantics",
        "Load sequencing and relationship resolution",
        "Reconciliation and proving a migration worked",
        "Error handling and partial failure",
        "Scheduled extracts and ETL patterns",
        "Change Data Capture and event-driven updates",
        "External objects and Salesforce Connect",
      ],
    },
    {
      title: "CRM Analytics",
      weekRange: "Weeks 6–7",
      description:
        "Salesforce's analytics platform, for the questions standard reports cannot answer. Datasets, dataflows and recipes; joining Salesforce data with external sources; SAQL basics; lenses, dashboards and bindings.\n\nSecurity gets particular attention because CRM Analytics has its own sharing model that does not inherit from the org automatically — a genuine source of accidental exposure. You build a dashboard answering a question that standard reporting cannot.",
      topics: [
        "Datasets, dataflows and recipes",
        "Joining Salesforce and external data",
        "SAQL basics and when you need it",
        "Lenses, dashboards and bindings",
        "Row-level security in CRM Analytics",
        "Why it does not inherit org sharing",
        "Scheduling and dataset refresh",
        "Choosing between standard reports and CRM Analytics",
      ],
    },
    {
      title: "Data Cloud Fundamentals",
      weekRange: "Week 8",
      description:
        "Unifying customer data across systems, which is the capability Agentforce and modern personalisation depend on. Data streams and ingestion; the data model and mapping to it; identity resolution and how a unified profile is actually assembled; calculated insights and segmentation.\n\nCovered honestly, including cost and complexity: Data Cloud is a substantial commitment and the right advice for many organisations is to fix their core data quality first.",
      topics: [
        "Data streams and ingestion sources",
        "The Data Cloud data model and mapping",
        "Identity resolution and unified profiles",
        "Calculated insights",
        "Segmentation and activation",
        "Data Cloud with Sales and Service Cloud",
        "Cost and complexity considerations",
        "When to fix core data quality first",
      ],
    },
    {
      title: "Tableau & Visual Analytics",
      weekRange: "Week 9",
      description:
        "Visualisation as a communication discipline. Connecting Tableau to Salesforce data; the grammar of building a view; calculated fields, table calculations and level-of-detail expressions; and dashboard design that answers a question rather than displaying everything available.\n\nThe standard taught is that a chart which requires explanation has failed, and that the choice of chart type is an argument about what matters.",
      topics: [
        "Connecting Tableau to Salesforce data",
        "Building views and the visual grammar",
        "Calculated fields and table calculations",
        "Level-of-detail expressions",
        "Choosing a chart type as an argument",
        "Dashboard layout and information hierarchy",
        "Interactivity, filters and actions",
        "Publishing, permissions and refresh",
      ],
    },
    {
      title: "Analytics Build & Certification Preparation",
      weekRange: "Week 10 + placement prep",
      description:
        "A full analytics build on your own messy dataset: a documented data model, a quality remediation, a reporting pack, a CRM Analytics dashboard, and a written note on what the data cannot answer and why — which is the part that reads as senior.\n\nAlongside it, preparation for the Data Cloud Consultant and CRM Analytics credentials, and mock interviews on data modelling, reporting constraints and quality scenarios.",
      topics: [
        "End-to-end analytics build",
        "Documenting a data model and its limitations",
        "Data Cloud Consultant exam preparation",
        "CRM Analytics credential preparation",
        "Mock interview — data modelling scenarios",
        "Mock interview — reporting and quality scenarios",
        "Presenting an analysis to a business audience",
        "Resume and LinkedIn for data roles",
      ],
    },
    {
      title: "AI, Agentforce & the Data It Needs",
      weekRange: "Final Week",
      description:
        "Why this specialisation matters more than it did. Agentforce grounds an agent on org and unified data, which means data quality, structure and governance now determine whether an AI feature works at all — the point our career guide makes when it says AI sits on top of strong CRM and data knowledge.\n\nCovered practically: what an agent needs from your data model, how grounding actually retrieves it, Einstein prediction features and their data requirements, and the governance questions to raise before any of it is switched on.",
      topics: [
        "How grounding retrieves org and unified data",
        "What an agent needs from your data model",
        "Data quality as the determinant of AI usefulness",
        "Einstein prediction features and their data requirements",
        "Segmentation and activation for AI use cases",
        "AI governance, consent and data privacy",
        "Advising honestly against premature AI adoption",
        "Using AI assistants for analysis and documentation",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-data-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Nine-stage Salesforce Data and Analytics learning path taught at Archer Infotech Pune: the Salesforce data model and platform foundations; data quality, governance and stewardship; reports and dashboards to analytical depth; data migration, loading and integration; CRM Analytics with datasets, recipes and row-level security; Data Cloud fundamentals covering ingestion, identity resolution and segmentation; Tableau and visual analytics; an analytics build with certification preparation; and AI and Agentforce with the data they require.",
    caption:
      "The order this course is taught in — the data model and its quality before anything is built on top. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-data-analytics-syllabus-v1.pdf",
    title: "Salesforce Data & Analytics Syllabus — Complete Module List",
    slug: "salesforce-data-analytics-syllabus",
    blurb:
      "All nine modules as a PDF — the Salesforce data model, data quality and governance, reporting to analytical depth, migration and integration, CRM Analytics, Data Cloud, Tableau, the analytics build with certification preparation, and the data foundations Agentforce depends on. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All nine modules in teaching order, each with its schedule, description and full topic list.",
          "Reporting taken well past where administrator courses stop — custom report types, joined reports, cross filters, row-level formulas and PARENTGROUPVAL.",
          "CRM Analytics, Data Cloud and Tableau covered as three distinct tools with a stated rule for choosing between them and standard reporting.",
          "Data quality treated as a measured discipline with a dashboard, not as a maintenance chore — because it is now the blocking dependency for AI.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Data Analyst and CRM Analytics specialist.",
          "Salesforce Data Cloud Consultant.",
          "Reporting and MIS lead in an organisation running Salesforce.",
          "The data grounding beneath the Architect path.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Data Quality Remediation with Measurement",
      description:
        "Take a deliberately degraded dataset — duplicates, inconsistent picklists, orphaned records, missing required data — profile it, quantify what is wrong, build the duplicate, matching and validation rules that stop it recurring, remediate the existing records, and produce a data quality dashboard tracking completeness and duplication over time. The measurement is the deliverable, not the cleanup.",
      technologies: [
        "Data profiling",
        "Duplicate and matching rules",
        "Data Loader and mass update",
        "Validation rules",
        "Data quality dashboard",
      ],
    },
    {
      title: "Analytics Build Answering a Real Question",
      description:
        "Choose a business question standard reporting cannot answer, then build what does answer it: a custom report type where needed, a CRM Analytics dataset joining Salesforce with external data, a dashboard with row-level security configured correctly, and a written note on what the data cannot tell you and why. That last part is what reads as senior at interview.",
      technologies: [
        "Custom report types",
        "CRM Analytics datasets and recipes",
        "Row-level security",
        "Tableau visualisation",
        "Documented limitations",
      ],
    },
  ],

  trainersIntro:
    "Sessions are led by a trainer who works with production Salesforce data rather than sample datasets. Your data model and dashboards are reviewed in your own org, including being questioned on what the numbers actually mean.",

  careerOutcomes: {
    paragraphs: [
      "Data-focused Salesforce roles in Pune sit with services majors on larger deliveries, with consulting partners running Data Cloud and analytics engagements, and inside enterprises with mature Salesforce estates. Postings appear as Salesforce Data Analyst, CRM Analytics Consultant, Data Cloud Consultant and increasingly as data-quality and governance roles.",
      "Demand has risen with the platform's AI direction, because an agent grounded on poor data is worse than no agent. That has moved data quality, unification and governance from background maintenance to the dependency everything else waits on — which is the strongest argument for this specialisation right now.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Data Analyst",
      "CRM Analytics Consultant",
      "Salesforce Data Cloud Consultant",
      "Reporting and MIS Lead",
      "Salesforce Data Governance Analyst",
      "BI Analyst on a Salesforce estate",
    ],
  },

  modesAndDuration: {
    duration: "3 months (11 weeks) for the weekday and online tracks; 13 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "Data Loader and Salesforce CLI (free)",
        "Tableau Public or a trial licence",
        "Trailhead and trailmixes (free)",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 13 weeks rather than 11 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Data & Analytics sits in the upper-mid band of our catalogue, reflecting a three-month duration and the tooling breadth. Salesforce examination fees are paid by you directly to Salesforce when you choose to sit, and are never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹38,000 – ₹52,000 (typical band) plus Salesforce examination fees, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week nine. By graduation your resume is rewritten for data roles, your analytics build is reviewed, and you have completed mock interviews covering data modelling and reporting-constraint scenarios.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 9 — resume and LinkedIn rewritten for data and analytics roles",
      "Week 10 — analytics build reviewed and presentation rehearsed",
      "Week 10 — first mock interview on data modelling scenarios",
      "Week 11 — second mock interview on reporting and data quality scenarios",
      "Week 11 — certification-readiness check",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Salesforce Data & Analytics or a general data analyst path?",
    paragraphs: [
      "A general data analytics path — SQL, Python, Power BI, warehousing — is broader, more portable and has far more openings. Our Data & AI category covers exactly that. This course is narrower and deeper: it is about customer data inside one platform, and the skills are worth a great deal inside the Salesforce ecosystem and less directly outside it.",
      "Take this path if you already work on Salesforce and want analytical depth, or if you already do data work and want a specialisation with less competition per posting. Take the general path if you are starting from nothing and want maximum optionality.",
      "The strongest position is both, and it is reachable: SQL and a visualisation tool transfer straight in, and Data Cloud work increasingly looks like warehouse work with a CRM-shaped schema. Several of our learners take the Data Analytics course in the Data & AI category first and this one afterwards.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "You need either data background or Salesforce background — not necessarily both. Data analysts and BI professionals arrive with the analytical craft and learn the platform; Salesforce administrators arrive with the platform and learn the analytical depth. What does not work is arriving with neither, in which case the Administrator course is the right starting point. Comfort with spreadsheets and basic SQL concepts helps considerably.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to see how the data path connects to the others",
      "Create a free Developer Edition org and build one report end to end",
      "Check the upcoming batch dates and pick a mode",
      "Book a free counselling session, particularly if you are coming from a non-Salesforce data background",
      "Enrol, and bring a laptop to session one",
    ],
  },

  faqs: [
    {
      question: "Do I need Salesforce experience before this course?",
      answer:
        "Either Salesforce experience or data experience — not necessarily both. Analysts and BI professionals learn the platform here; administrators learn the analytical depth. If you have neither, take the Administrator course first, because this course assumes you can navigate an org or read a dataset without help on one of the two sides.",
    },
    {
      question: "What is Data Cloud, and do I need it?",
      answer:
        "Data Cloud unifies customer data from Salesforce and external systems into resolved profiles that other tools — including Agentforce — can use. It is a substantial commitment in both cost and complexity. This course covers it honestly, including the advice we would give many organisations: fix core data quality first, because unifying poor data produces unified poor data.",
    },
    {
      question: "Is CRM Analytics the same as Tableau?",
      answer:
        "No, and the distinction matters in interviews. CRM Analytics is Salesforce's native analytics platform, tightly bound to the org with its own dataflows and its own security model. Tableau is a general visualisation platform Salesforce acquired, which connects to many sources. This course covers both and gives you a rule for choosing between them and standard reports.",
    },
    {
      question: "Why does data quality matter more now than it used to?",
      answer:
        "Because Agentforce grounds AI agents on your org and unified data. An agent answering from poor data is worse than no agent — it is confidently wrong at scale. That has moved data quality from unglamorous maintenance to the dependency everything else waits on, which is the single strongest argument for this specialisation in 2026.",
    },
    {
      question: "Which certification does this path lead to?",
      answer:
        "Data Cloud Consultant and the CRM Analytics credentials are the closest role-based fits, and this course prepares for both. The Administrator credential is worth holding first if you came from a data rather than a Salesforce background, because it demonstrates the platform literacy these exams assume.",
    },
    {
      question: "Will I work with real, messy data?",
      answer:
        "Yes, deliberately. You load an imperfect dataset in week one — duplicates, inconsistent picklists, orphaned records — and it stays with you for the rest of the course. Clean sample data teaches you the tool and not the job, and the first month of a real data role is almost entirely about the mess.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Data & Analytics training in Pune?",
    paragraph:
      "Three months from now you can have a remediated dataset with a quality dashboard measuring it, a CRM Analytics build answering a question standard reports could not, a documented data model, and a clear run at the Data Cloud Consultant exam. Bring either data background or Salesforce background. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
