import type { CourseRichContent } from "./types";

/**
 * Salesforce Architect — rich content overlay.
 *
 * Path 8 of the eight in the Salesforce Career Guide 2026. The guide states
 * that architecture is a five to eight year destination and 'not a course
 * you enrol in'. This page is scoped as a preparation track for people
 * already at that stage rather than as an entry course, and says so on the
 * page itself.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceArchitectTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Architect covers application, data and integration architecture, security and identity, performance and scalability, governance, and increasingly AI architecture. Our Salesforce Career Guide 2026 is blunt about this one: architecture is a five to eight year destination, not a fresher starting point, and not a course you enrol in your way to. This programme is scoped accordingly — a four-month preparation track for experienced developers, consultants and lead administrators who are already doing parts of the job and want the structure, the design vocabulary and a route toward the Architect credentials.",

  whyLearn: {
    heading: "Who This Track Is Actually For",
    paragraphs: [
      "We are going to be direct, because our own career guide is. You cannot become a Salesforce architect by taking a course. Architecture is judgement accumulated across many implementations, and the judgement is the product — a person who has memorised integration patterns and never watched one fail in production is not an architect and will be found out in the first design review. Anyone selling a four-month path from beginner to architect is selling you something that does not exist.",
      "What a structured programme genuinely does help with is different and narrower. Experienced practitioners frequently hold the knowledge in fragments — deep in the areas they have shipped, thin in the ones they have not — and have no shared vocabulary for design decisions they make correctly by instinct. This track supplies the structure, fills the specific gaps, and prepares for the Architect credential path, which is a real and difficult exam route that rewards preparation.",
      "So the honest positioning: this is for people already five or more years into the platform who are doing architecture work informally and want to formalise it. If that is not you yet, the useful thing we can tell you is which path to take now — Developer, Consultant or Data & Analytics depending on where your interest sits — and the fact that this track will still be here when you are ready. We would rather say that than take a fee.",
    ],
    keyPoints: [
      "A preparation track for experienced practitioners, not an entry course",
      "Our career guide places architecture at five to eight years of experience",
      "Aligned to the Salesforce Architect credential path",
      "Supplies structure and design vocabulary to knowledge you already hold in fragments",
      "Integration, data and security architecture given the most weight",
      "Indicative architect band ₹25–45+ LPA, reached through experience rather than a course",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "Salesforce developers with five or more years, doing design work informally",
      "Senior consultants who own solution design across multiple client engagements",
      "Lead administrators responsible for a large or multi-org estate",
      "Technical leads preparing for the Salesforce Architect credential path",
      "Integration and platform engineers with substantial Salesforce exposure",
    ],
    notForYou: [
      "Freshers and career changers — architecture is a five to eight year destination, and our career guide says so plainly",
      "Anyone with under about five years on the platform; the track assumes production scars, not just knowledge",
      "Candidates hoping a certification alone will produce an architect title; it will not, and hiring managers know",
      "People who want to keep building rather than deciding — senior developer is a perfectly good career and pays well",
    ],
  },

  curriculum: [
    {
      title: "What an Architect Is Accountable For",
      weekRange: "Week 1",
      description:
        "The remit, and the shift that people moving up find hardest. An architect is accountable for decisions whose consequences arrive in two years, made with incomplete information, and defended to people who each want something different. The deliverable is a decision plus the reasoning, not a build.\n\nThe architect specialisms — application, integration, data, security, identity, system — and how they connect. You bring a real design you have made and the course examines it.",
      topics: [
        "What an architect owns beyond a solution design",
        "Deciding under incomplete information",
        "Architecture decision records and reasoning",
        "The architect specialisms and how they connect",
        "Domain architect versus technical architect",
        "Working with enterprise architecture functions",
        "Governance bodies and design authority",
        "Presenting a design examination of your own work",
      ],
    },
    {
      title: "Application Architecture & Large-Scale Design",
      weekRange: "Weeks 2–3",
      description:
        "Designing something that survives its third year and its fourth team. Declarative-versus-programmatic as an architectural policy rather than a per-story decision; separation of concerns in Apex; and the trigger, service and domain layer patterns that keep a large org's code navigable.\n\nSingle-org against multi-org: the arguments on both sides, the org-merge scenario, and why the answer is usually organisational rather than technical. Package strategy, technical debt as an actively managed quantity, and designing explicitly for the team that inherits it.",
      topics: [
        "Declarative-versus-programmatic as policy",
        "Separation of concerns and Apex layering",
        "Trigger, service and domain patterns at scale",
        "Single-org versus multi-org strategy",
        "Org merge and divestiture scenarios",
        "Unlocked packages and modularisation",
        "Technical debt as a managed quantity",
        "Designing for the team that inherits the org",
        "Reference architectures and standards",
      ],
    },
    {
      title: "Data Architecture & Large Data Volumes",
      weekRange: "Weeks 3–4",
      description:
        "Where Salesforce architecture becomes genuinely specialised. Data modelling for scale, skew — ownership, lookup and account data skew — and the locking and sharing-recalculation problems each causes at volume.\n\nLarge data volume techniques: selective queries, custom indexes, skinny tables, divisions, archiving strategy and the mechanics of sharing recalculation. Master data management, system of record decisions across an estate, and data retention and residency under Indian and international requirements.",
      topics: [
        "Data modelling for scale",
        "Ownership, lookup and account data skew",
        "Record locking and sharing recalculation",
        "Selective queries and custom indexes",
        "Skinny tables and divisions",
        "Archiving and data lifecycle strategy",
        "Master data management and system of record",
        "Data retention, residency and sovereignty",
        "Data Cloud in an architecture",
      ],
    },
    {
      title: "Integration Architecture",
      weekRange: "Weeks 5–6",
      description:
        "The specialism that most defines a Salesforce architect's value. The integration patterns — request-reply, fire-and-forget, batch data synchronisation, remote call-in, UI update based on data changes — with the capability, limits and failure behaviour of each.\n\nMiddleware and enterprise service bus decisions; event-driven architecture with platform events and Change Data Capture; API limit budgeting across an estate; and error handling, retry, idempotency and reconciliation at a scale where a failed message cannot simply be re-run by hand.",
      topics: [
        "The Salesforce integration patterns and their limits",
        "Choosing a pattern from volume, latency and coupling",
        "Middleware and enterprise service bus decisions",
        "Event-driven architecture at estate scale",
        "Platform events and Change Data Capture",
        "API limit budgeting across integrations",
        "Error handling, retry and idempotency",
        "Reconciliation and eventual consistency",
        "Integration security and credential management",
      ],
    },
    {
      title: "Identity & Access Management Architecture",
      weekRange: "Week 7",
      description:
        "Identity as an architectural domain rather than a configuration task. SAML, OAuth 2.0 flows and OpenID Connect; single sign-on with Salesforce as service provider and as identity provider; just-in-time provisioning and SCIM.\n\nExternal identity for customer and partner communities, delegated authentication, and the session and device policies that follow. Designed against real constraints — a workforce identity provider, a customer base, and an audit requirement that all three must satisfy simultaneously.",
      topics: [
        "SAML and assertion handling",
        "OAuth 2.0 flows and choosing between them",
        "OpenID Connect and identity federation",
        "Salesforce as service provider and identity provider",
        "Just-in-time provisioning and SCIM",
        "External identity for communities",
        "Delegated authentication",
        "Session, device and MFA policy",
        "Designing identity against audit requirements",
      ],
    },
    {
      title: "Security Architecture & Compliance",
      weekRange: "Week 8",
      description:
        "Security designed rather than configured. The sharing architecture at scale — organisation-wide defaults, hierarchy, sharing rules, apex sharing and territory-driven access — and how to keep it comprehensible when several mechanisms overlap.\n\nPlatform encryption and its functional trade-offs, Event Monitoring and Shield, field audit trail, and designing to a compliance requirement rather than to a checklist. Threat modelling for a Salesforce estate closes the module.",
      topics: [
        "Sharing architecture at scale",
        "Apex sharing and manual sharing at volume",
        "Territory-driven access design",
        "Platform encryption and its trade-offs",
        "Shield, Event Monitoring and audit trail",
        "Designing to a compliance requirement",
        "Threat modelling a Salesforce estate",
        "Third-party and AppExchange risk assessment",
        "Security review for managed packages",
      ],
    },
    {
      title: "Performance, Scalability & Resilience",
      weekRange: "Week 9",
      description:
        "Making it hold up. Governor limits as an architectural budget across an estate rather than a per-transaction constraint; asynchronous design and queue management; and the performance characteristics of large orgs that behave nothing like a development environment.\n\nLoad testing, monitoring and observability; disaster recovery, backup and the honest position that Salesforce's own backup provisions are not a recovery strategy; and release and environment strategy across a large delivery organisation.",
      topics: [
        "Governor limits as an estate-level budget",
        "Asynchronous design and queue management",
        "Performance characteristics of large orgs",
        "Load testing and profiling approaches",
        "Monitoring and observability",
        "Backup, recovery and Salesforce's actual provisions",
        "Business continuity and disaster recovery",
        "Release and environment strategy at scale",
        "Sandbox strategy for a large programme",
      ],
    },
    {
      title: "AI Architecture — Agentforce, Data Cloud & Governance",
      weekRange: "Week 10",
      description:
        "The newest architectural domain, and one where the honest answers matter most because organisations are buying ahead of readiness. Agentforce architecture — agents, actions, grounding and the data path behind them — and what has to be true before any of it produces value.\n\nData Cloud in an enterprise architecture, AI governance, model and prompt security, prompt injection in an agent that holds real permissions, and the consent and privacy requirements. The recurring architectural answer is the one our career guide gives: AI sits on top of strong CRM, data and platform foundations, and an architect's job is often to say so.",
      topics: [
        "Agentforce architecture — agents, actions, grounding",
        "The data path behind a grounded agent",
        "Data Cloud in an enterprise architecture",
        "AI governance and model risk",
        "Prompt injection in an agent holding permissions",
        "Action scoping and least privilege for agents",
        "Consent, privacy and AI data flows",
        "Evaluating AI readiness honestly",
        "Advising against premature AI investment",
      ],
      highlight: true,
    },
    {
      title: "Design Reviews, Communication & Influence",
      weekRange: "Week 11",
      description:
        "The half of architecture that has nothing to do with the platform. Running a design review that surfaces the real risk rather than performing agreement; presenting to a steering committee; and writing an architecture decision record someone can follow after you have left.\n\nInfluence without authority — an architect usually cannot instruct anyone — and the specific skill of disagreeing with a senior stakeholder while keeping the relationship. Practised through review role-play on each other's designs.",
      topics: [
        "Running a design review that surfaces real risk",
        "Presenting architecture to a steering committee",
        "Architecture decision records that outlive you",
        "Influence without direct authority",
        "Disagreeing with a senior stakeholder",
        "Trade-off communication to non-technical audiences",
        "Mentoring developers and consultants",
        "Building consensus across delivery teams",
      ],
    },
    {
      title: "Architect Credential Preparation & Portfolio",
      weekRange: "Week 12 + review cycle",
      description:
        "Preparation for the Architect credential path — the domain architect examinations and the review-board format, which assesses a presented design under questioning rather than a multiple-choice paper and is a genuinely different discipline.\n\nYou build and present a full reference architecture for a complex scenario: data model, integration landscape, identity design, security architecture, scalability approach and a documented set of decisions with their trade-offs. Reviewed the way a board reviews.",
      topics: [
        "The Architect credential path and its structure",
        "Domain architect examination preparation",
        "The review-board format and what it assesses",
        "Building a full reference architecture",
        "Documenting decisions and trade-offs",
        "Presenting under sustained questioning",
        "Handling a challenge you had not anticipated",
        "Portfolio of architecture work for interviews",
      ],
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-architect-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Ten-stage Salesforce Architect preparation track taught at Archer Infotech Pune for experienced practitioners: what an architect is accountable for; application architecture and large-scale design; data architecture and large data volumes covering skew and selective queries; integration architecture covering the Salesforce integration patterns and event-driven design; identity and access management architecture covering SAML, OAuth and single sign-on; security architecture and compliance; performance, scalability and resilience; AI architecture covering Agentforce, Data Cloud and governance; design reviews, communication and influence; and Architect credential preparation with a reference architecture portfolio.",
    caption:
      "A preparation track for experienced practitioners, not an entry route. Our career guide places architecture at five to eight years — each stage below assumes you have already shipped things at that level.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-architect-syllabus-v1.pdf",
    title: "Salesforce Architect Syllabus — Complete Module List",
    slug: "salesforce-architect-syllabus",
    blurb:
      "All eleven modules as a PDF — the architect remit, application architecture at scale, data architecture and large data volumes, integration architecture, identity and access management, security and compliance, performance and resilience, AI architecture with Agentforce, design review and influence, and Architect credential preparation. Scoped as a preparation track for experienced practitioners, and it says so. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All eleven modules in teaching order, each with its schedule, description and full topic list.",
          "The experience gate stated at the front — roughly five years on the platform — in line with our Salesforce Career Guide 2026, which places architecture at a five to eight year destination.",
          "Integration and data architecture given the most weight, including large data volume techniques, skew, sharing recalculation and API limit budgeting across an estate.",
          "The review-board format explained, which assesses a presented design under sustained questioning rather than a multiple-choice paper and is a genuinely different discipline to prepare for.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Technical Architect and Solution Architect.",
          "Salesforce Integration Architect and Data Architect.",
          "Domain architect on a large Salesforce estate.",
          "Practice or engineering lead with architectural accountability.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Reference Architecture for a Complex Estate",
      description:
        "Produce and defend a complete architecture for a demanding scenario — multi-org or post-merger, high data volume, several integrations, an external customer identity requirement and a compliance obligation. Data model, integration landscape, identity design, security architecture, scalability approach, and a set of decision records each stating the alternatives considered and why they were rejected. Presented under sustained questioning, in the review-board format.",
      technologies: [
        "Data and integration architecture",
        "Identity and access design",
        "Security architecture",
        "Scalability and resilience planning",
        "Architecture decision records",
        "Design defence under questioning",
      ],
    },
    {
      title: "Architectural Assessment of a Live Estate",
      description:
        "Assess a large org against the domains covered in the course — application layering, data volume and skew, integration reliability, sharing comprehensibility, release process, backup and recovery — and produce the remediation roadmap with sequencing, effort and risk. The engagement senior architects are most often brought in to perform.",
      technologies: [
        "Org and estate assessment",
        "Technical debt quantification",
        "Risk identification and sequencing",
        "Remediation roadmap",
        "Executive-level reporting",
      ],
    },
  ],

  trainersIntro:
    "Sessions are led by a practitioner who has held architectural accountability on live Salesforce estates rather than only studied the credential path. Your designs are challenged the way a review board challenges them, which is uncomfortable by design.",

  careerOutcomes: {
    paragraphs: [
      "Salesforce architecture roles in Pune sit with the services majors' Salesforce practices, the larger Salesforce-native partners and enterprises with substantial estates. Postings appear as Salesforce Technical Architect, Solution Architect, Integration Architect and Data Architect — and almost all of them specify years of hands-on experience rather than credentials alone.",
      "The important thing to be honest about is causation. Architects earn at the top of the ecosystem's range because of what they have done, not because of the credential — the credential recognises the capability rather than creating it. Our career guide places this as a five to eight year target for exactly that reason, and this track is preparation for people already approaching it, not a shortcut past it.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Salesforce Technical Architect",
      "Salesforce Solution Architect",
      "Salesforce Integration Architect",
      "Salesforce Data Architect",
      "Practice Lead with architectural accountability",
      "Enterprise Architect covering a Salesforce estate",
    ],
  },

  modesAndDuration: {
    duration: "4 months (12 weeks plus a review cycle) for the weekday and online tracks; 14 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition orgs, including multi-org scenarios",
        "Architecture diagramming tools",
        "Trailhead architect trailmixes (free)",
        "Slack batch channel for design discussion",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 14 weeks rather than 12 to keep total contact hours the same. Most learners on this track take the weekend or online format, since almost everyone is working full time.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Architect sits at the top of our catalogue, reflecting a four-month duration and the seniority of the practitioner required to teach it. Salesforce Architect credential examination fees are paid by you directly to Salesforce and are substantially higher than associate-level exams, particularly the review-board component — they are never bundled into or marked up in our fee. EMI is available; contact admissions for the current figure.",
    range: "₹55,000 – ₹80,000 (typical band) plus Salesforce Architect examination fees, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support on this track looks different from our entry courses, because nobody arrives here needing a first job. The work is positioning — turning a senior developer or consultant CV into an architect one, rehearsing the design stories an architect interview explores, and introductions where a practice is genuinely hiring at that level. Architect openings are few and specific, and we will not pretend otherwise.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 10 — CV repositioned from senior practitioner to architect",
      "Week 11 — reference architecture reviewed and presentation rehearsed",
      "Week 12 — design defence under sustained questioning",
      "Review cycle — credential-path readiness assessment",
      "Post-course — introductions where a practice is hiring at architect level",
      "Post-course weeks 1–24 — continued design review and credential coaching",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Architect or Consultant — and are you ready for either?",
    paragraphs: [
      "Both are progression tracks. Consulting moves you toward commercial and client ownership — scoping, delivering, being accountable for an outcome someone is paying for. Architecture moves you toward technical ownership of integration, data, identity and security across an estate. Different working days, and the choice is worth making deliberately.",
      "The timelines are what most people get wrong. Consulting is reachable at roughly two years of platform experience. Architecture, as our career guide states, is realistically a five to eight year destination. Taking consulting first and architecture later is a common and sensible sequence — delivery experience makes architectural judgement better, not worse.",
      "If you are earlier than either, the honest advice is the same one the guide gives: pick Developer, Business Analyst or Data & Analytics based on where your interest sits, spend a few years shipping, and come back. Nobody has ever been hired as an architect on the strength of a course, and we would rather tell you that at the counselling session than after you have paid.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "This track assumes roughly five years of hands-on Salesforce experience — as a developer, senior consultant or lead administrator on a substantial estate — plus existing certifications and, more importantly, production experience of things going wrong. The gate is real and we apply it at the counselling session. Our Salesforce Career Guide 2026 says architecture is a five to eight year destination and not a course you enrol in, and we are not going to contradict our own published advice to sell a seat. If you are earlier than this, we will tell you which path to take now and this one will still be here.",
    ],
    suggestedSteps: [
      "Confirm you meet the experience gate — roughly five years hands-on, with production responsibility",
      "Read the Salesforce Career Guide 2026 on our blog, particularly the section on the architect path",
      "Book a counselling session; for this track it is a readiness assessment and we do turn applications away",
      "Bring a real architecture you have worked on — the first week examines it",
      "Enrol, and expect your designs to be challenged rather than approved",
    ],
  },

  faqs: [
    {
      question: "Can I become a Salesforce Architect by taking this course?",
      answer:
        "No, and anyone telling you otherwise is selling something that does not exist. Architecture is judgement accumulated across many implementations — this track supplies structure, design vocabulary and credential preparation to people who are already accumulating it. Our own career guide calls architecture a five to eight year destination and says plainly it is not a course you enrol in. We are not going to contradict our own published advice.",
    },
    {
      question: "How much experience do I really need?",
      answer:
        "Roughly five years hands-on, as a developer, senior consultant or lead administrator on a substantial estate — and more importantly, production experience of things going wrong. Reading about record locking is different from having caused it. We assess this at the counselling session and we do turn applications away, which we would rather do than take a fee for something you cannot yet use.",
    },
    {
      question: "What is the review board, and how is it different from a normal exam?",
      answer:
        "The Architect credential path culminates in a review board where you present a design for a complex scenario and defend it under sustained questioning from practising architects. It assesses whether you can reason about trade-offs live, not whether you can recognise a correct option. It is a genuinely different discipline to prepare for, which is why week twelve is built around presenting and defending rather than answering papers.",
    },
    {
      question: "Is the Architect certification worth the cost?",
      answer:
        "Only if you are already doing the work. The credential recognises capability rather than creating it, and the exam fees — particularly the review-board component — are substantially higher than associate-level exams. For a practitioner already holding architectural accountability it formalises and is well regarded. For someone hoping it will produce the title, it will not, and hiring managers at this level are not fooled by it.",
    },
    {
      question: "Which architect specialism should I aim for?",
      answer:
        "Follow what you have actually done. Integration architecture is the most consistently in demand and the hardest for employers to fill. Data architecture has grown sharply with Data Cloud and the AI direction. Application architecture suits people from a development background, and identity and security suit those who have worked on enterprise access. The domain credentials map to these, and the course covers all of them because architects are expected to be literate across the set.",
    },
    {
      question: "What should I do if I am not ready for this track?",
      answer:
        "Take the path that matches where your interest sits — Developer if you want to build, Consultant if you want client and delivery ownership, Data & Analytics if the data side is what draws you — and spend a few years shipping real work. That is the actual route, and it is the one our career guide describes. Come back when you have production scars; this track will still be here, and you will get considerably more from it.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Considering the Salesforce Architect track?",
    paragraph:
      "This is a preparation track for experienced practitioners, not an entry route — our career guide places architecture at five to eight years, and we apply that as a real gate. If you are already holding architectural accountability informally and want the structure, the design vocabulary and a route toward the Architect credentials, book a counselling session and we will assess readiness honestly. If you are earlier than that, we will tell you which path to take now instead.",
  },
};
