import type { CourseRichContent } from "./types";

/**
 * Salesforce Sales Cloud — rich content overlay.
 *
 * Path 7 of the eight in the Salesforce Career Guide 2026. The sales-
 * process specialisation — leads, opportunities, forecasting, sales
 * automation — aimed at the sales professionals and MBA Sales and Marketing
 * graduates the guide names.
 *
 * Generated by scripts/build-salesforce-courses.py. Operational blocks are
 * shared across the eight Salesforce paths by design; edit the generator
 * rather than this file.
 */

export const salesforceSalesCloudTrainingInPune: CourseRichContent = {
  intro:
    "Salesforce Sales Cloud is the specialisation for people who understand selling and want to own the platform that runs it: leads and opportunities, sales process design, forecasting, quoting, territory management, sales automation and AI-assisted selling. It is the shortest route into the ecosystem for someone with a sales or sales-operations background, because you already know what the software is supposed to support. Two months, hands-on in your own org, aligned to the Administrator and Sales Cloud Consultant credentials.",

  whyLearn: {
    heading: "Why Learn Salesforce Sales Cloud in Pune in 2026",
    paragraphs: [
      "Sales Cloud is Salesforce's original and still largest product, which means almost every org in Pune runs it and almost every implementation needs someone who understands the sales process rather than only the configuration screens. That person is unusually valuable and unusually rare: most administrators learn the platform and pick up sales concepts second, which is the harder direction.",
      "If you come from sales, sales operations or business development, you already hold the half that cannot be taught quickly — knowing why a stage exists, what a forecast category actually means to a sales director, and which fields a rep will refuse to fill in. This course adds the platform to that, which is the shorter half of the journey.",
      "The role sits close to the business, which suits people who like that and is worth knowing if you do not. Sales Cloud specialists spend their time with sales leadership, in pipeline reviews and in the argument about why forecast accuracy is poor. It leads naturally toward consulting, sales operations leadership or revenue operations.",
    ],
    keyPoints: [
      "The shortest route in for people with a sales or sales-operations background",
      "Sales Cloud runs in almost every Salesforce org in Pune",
      "Aligned to the Administrator and Sales Cloud Consultant credentials",
      "Sales process judgement is the half that cannot be taught quickly — you may already have it",
      "Leads toward consulting, sales operations and revenue operations",
      "Indicative 1–3 year band ₹6–12 LPA",
    ],
  },

  whoIsThisFor: {
    forYou: [
      "Sales professionals and business development executives moving into a platform role",
      "Sales operations and revenue operations staff who already work inside Salesforce",
      "MBA Sales and Marketing graduates entering technology",
      "Salesforce administrators specialising toward Sales Cloud delivery",
      "CRM users at any organisation running Salesforce for sales",
    ],
    notForYou: [
      "Anyone wanting service, marketing or development work — those are separate paths",
      "Candidates with no interest in sales process, since that is the substance of the role",
      "Learners looking for a broad administrator qualification — the Administrator course covers more ground",
    ],
  },

  curriculum: [
    {
      title: "Sales Process & the Salesforce Sales Model",
      weekRange: "Week 1",
      description:
        "The business before the platform. Sales methodologies and how they map to a pipeline; the lead-to-cash process end to end; and the difference between a sales process that reflects how deals actually close and one that reflects how management wishes they did.\n\nYou set up your own org and configure a first pipeline against a documented process, establishing the standard for the rest of the course: every configuration decision traces to a stated business reason.",
      topics: [
        "Sales methodologies and pipeline design",
        "Lead-to-cash end to end",
        "Setting up your own Salesforce org",
        "Standard objects — leads, accounts, contacts, opportunities",
        "Record types and multiple sales processes",
        "Designing stages that reflect reality",
        "Sales roles, hierarchy and visibility",
        "Configuring against a documented process",
      ],
    },
    {
      title: "Lead Management & Conversion",
      weekRange: "Week 2",
      description:
        "The top of the funnel. Lead capture from web, campaigns and imports; assignment rules and round-robin distribution; qualification criteria and lead scoring; and conversion — including the mapping decisions people get wrong once and then live with.\n\nDuplicate management gets real attention here because leads are where duplicates enter an org, and a duplicate at the lead stage becomes a duplicate account, contact and opportunity later.",
      topics: [
        "Web-to-Lead and campaign capture",
        "Lead assignment rules and queues",
        "Round-robin and territory-based distribution",
        "Qualification criteria and lead scoring",
        "Lead conversion and field mapping",
        "Duplicate and matching rules at lead stage",
        "Lead nurture handover to marketing",
        "Lead source tracking and attribution",
      ],
    },
    {
      title: "Opportunity Management & Sales Path",
      weekRange: "Week 3",
      description:
        "The core of the platform. Opportunity stages, probability and the sales path with guidance for each step; products and price books; opportunity teams and splits; and competitor and loss-reason tracking that actually gets filled in.\n\nThe recurring theme is adoption: every required field is a tax on a salesperson's time, and a beautifully designed process nobody follows produces worse data than a simple one they do.",
      topics: [
        "Opportunity stages, probability and close date",
        "Sales path and in-app guidance",
        "Products, price books and schedules",
        "Opportunity teams and splits",
        "Competitor and loss-reason tracking",
        "Required fields and the adoption cost",
        "Opportunity contact roles",
        "Designing for a salesperson's actual day",
      ],
    },
    {
      title: "Quoting, Contracts & Order Management",
      weekRange: "Week 4",
      description:
        "From an agreed price to a committed order. Quotes, quote line items, quote templates and approval; discounting rules and the approval chain; contracts and renewals; and orders.\n\nCPQ is covered at awareness level — what it solves, when an organisation genuinely needs it, and why it is a separate specialisation rather than a feature you switch on.",
      topics: [
        "Quotes and quote line items",
        "Quote templates and PDF generation",
        "Discount rules and approval processes",
        "Contracts, renewals and lifecycle",
        "Orders and order products",
        "CPQ awareness — what it solves and when it is needed",
        "Pricing governance",
        "Approval process design",
      ],
    },
    {
      title: "Forecasting, Territories & Sales Analytics",
      weekRange: "Week 5",
      description:
        "What sales leadership actually asks for. Collaborative forecasting, forecast categories and hierarchy; quota management; and the reasons forecasts are inaccurate, most of which are process rather than platform problems.\n\nTerritory management covers models, assignment rules and the realignment exercise every growing sales organisation goes through. Reporting covers pipeline, velocity, conversion and the dashboards a sales director will actually open.",
      topics: [
        "Collaborative forecasting and categories",
        "Forecast hierarchy and adjustments",
        "Quota management",
        "Why forecasts are inaccurate — process versus platform",
        "Enterprise territory management",
        "Territory assignment and realignment",
        "Pipeline, velocity and conversion reporting",
        "Dashboards a sales director will open",
      ],
    },
    {
      title: "Sales Automation & Productivity",
      weekRange: "Week 6",
      description:
        "Removing the work salespeople resent. Flow automation for stage-driven tasks, follow-up reminders and handovers; email integration with Outlook and Gmail; activity capture; templates and cadences.\n\nThe judgement taught is restraint again: automation that fires too often gets ignored, and an alert nobody reads is worse than no alert because it teaches people to ignore the channel.",
      topics: [
        "Flow automation for sales processes",
        "Stage-driven task and reminder creation",
        "Approval processes for exceptions",
        "Outlook and Gmail integration",
        "Activity capture and logging",
        "Email templates and cadences",
        "Notification design and alert fatigue",
        "Mobile app configuration for field sales",
      ],
    },
    {
      title: "Adoption, Data Quality & Sales Operations",
      weekRange: "Week 7",
      description:
        "Why Salesforce implementations fail after go-live. Adoption measurement, the behaviours that indicate a rep has stopped trusting the system, and the intervention that works — which is usually removing a required field rather than adding a training session.\n\nData quality from a sales perspective: duplicate accounts, stale opportunities, close dates pushed indefinitely, and the hygiene process that keeps a pipeline believable.",
      topics: [
        "Measuring adoption honestly",
        "Signals that reps have stopped trusting the system",
        "Reducing friction rather than adding training",
        "Duplicate account and contact management",
        "Stale opportunity and close-date hygiene",
        "Pipeline believability and clean-up cadence",
        "Sales operations cadence and reporting rhythm",
        "Working with sales leadership",
      ],
    },
    {
      title: "Build, Certification & Interview Preparation",
      weekRange: "Week 8 + placement prep",
      description:
        "A complete Sales Cloud configuration for a documented business, built in your org and presented as a walkthrough — which is exactly the interview format for this role.\n\nAlongside it, preparation for the Administrator credential as the foundation and the Sales Cloud Consultant credential as the specialisation, with timed mocks and mock interviews on sales process and forecasting scenarios.",
      topics: [
        "End-to-end Sales Cloud configuration",
        "Org walkthrough as an interview format",
        "Administrator exam preparation",
        "Sales Cloud Consultant exam preparation",
        "Timed mock papers and gap closure",
        "Mock interview — sales process design scenarios",
        "Mock interview — forecasting and reporting scenarios",
        "Resume and LinkedIn for Sales Cloud roles",
      ],
    },
    {
      title: "Einstein for Sales & Agentforce",
      weekRange: "Final Week",
      description:
        "AI-assisted selling, and what it actually requires. Einstein lead and opportunity scoring, activity capture, conversation insights and forecasting — each with the data volume and quality it needs, which is the part vendors gloss over and salespeople notice immediately when it is missing.\n\nAgentforce is covered at the level of what a sales organisation is being offered and what has to be true first. The career guide's caveat applies directly: scoring built on a pipeline full of stale opportunities predicts nothing useful.",
      topics: [
        "Einstein lead and opportunity scoring",
        "Data volume and quality each feature requires",
        "Einstein Activity Capture",
        "Conversation and call insights",
        "Einstein forecasting",
        "Agentforce in a sales context",
        "Why scoring on a stale pipeline is worthless",
        "Advising honestly on AI readiness",
        "Rep trust and explainability of AI suggestions",
      ],
      highlight: true,
    },
  ],

  roadmapImage: {
    src: "/images/courses/salesforce-sales-path-v1.webp",
    width: 1400,
    height: 900,
    alt: "Nine-stage Salesforce Sales Cloud learning path taught at Archer Infotech Pune: sales process and the Salesforce sales model; lead management and conversion; opportunity management and sales path; quoting, contracts and order management; forecasting, territories and sales analytics; sales automation and productivity; adoption, data quality and sales operations; a configuration build with certification preparation; and Einstein for sales with Agentforce.",
    caption:
      "The order this course is taught in — the sales process before the configuration, because a pipeline configured without one is just fields. Each stage expands into the modules below.",
  },

  syllabusDownload: {
    pdfUrl: "/downloads/salesforce-sales-cloud-syllabus-v1.pdf",
    title: "Salesforce Sales Cloud Syllabus — Complete Module List",
    slug: "salesforce-sales-cloud-syllabus",
    blurb:
      "All nine modules as a PDF — sales process design, lead management and conversion, opportunity management, quoting and contracts, forecasting and territories, sales automation, adoption and data quality, the configuration build with certification preparation, and Einstein for sales. Generated from this page, so the two cannot disagree.",
    asideBlocks: [
      {
        heading: "What is inside the PDF",
        items: [
          "All nine modules in teaching order, each with its schedule, description and full topic list.",
          "Sales process design treated as the foundation rather than a preamble, including the difference between a process that reflects how deals close and one that reflects how management wishes they did.",
          "Forecasting and territory management in depth, including the honest account of why forecasts are inaccurate — which is usually process, not platform.",
          "Adoption and data quality given a full module, because that is where Sales Cloud implementations fail after go-live.",
        ],
      },
      {
        heading: "Roles this syllabus prepares you for",
        items: [
          "Salesforce Sales Cloud Consultant.",
          "Sales Operations and Revenue Operations Analyst.",
          "Salesforce Administrator with a Sales Cloud specialisation.",
          "CRM Manager in a sales organisation running Salesforce.",
        ],
      },
    ],
  },

  projects: [
    {
      title: "Complete Sales Cloud Configuration",
      description:
        "Configure a full sales process for a documented business: lead capture and assignment, qualification and conversion, opportunity stages with a sales path, products and price books, quoting with an approval chain, forecasting with categories and quotas, and a dashboard pack for sales leadership. Presented as an org walkthrough, which is the interview format for this role.",
      technologies: [
        "Sales process and stage design",
        "Lead assignment and conversion",
        "Products, price books and quotes",
        "Approval processes",
        "Collaborative forecasting",
        "Reports and dashboards",
      ],
    },
    {
      title: "Adoption Rescue on a Neglected Pipeline",
      description:
        "Take an org with a believable adoption problem — stale opportunities, close dates pushed repeatedly, duplicate accounts, required fields reps work around — and produce the assessment and fix: what the data says about behaviour, which friction to remove, what to automate, and the hygiene cadence that keeps the pipeline honest. The problem sales operations is actually hired to solve.",
      technologies: [
        "Adoption reporting",
        "Duplicate management",
        "Pipeline hygiene rules",
        "Flow automation",
        "Sales operations cadence",
      ],
    },
  ],

  trainersIntro:
    "Sessions are led by a trainer who has configured Sales Cloud for real sales teams, including the ones who resisted it. Your configuration is reviewed in your own org and challenged on whether a salesperson would actually use it.",

  careerOutcomes: {
    paragraphs: [
      "Sales Cloud is the most widely deployed Salesforce product, so the specialisation travels across almost every organisation running the platform in Pune — services majors, consulting partners and enterprises with in-house teams. Postings appear as Sales Cloud Consultant, Sales Operations Analyst, Revenue Operations Analyst and Salesforce Administrator with a Sales Cloud emphasis.",
      "The progression from here is unusually broad: consulting once implementation experience accumulates, sales operations leadership, or revenue operations, which increasingly owns the whole commercial technology stack. What moves the band is business credibility with sales leadership as much as platform depth.",
      "Salary varies with experience, certification, development skill, cloud specialisation, company tier, communication and domain knowledge. The bands below mirror the India-oriented ranges in our Salesforce Career Guide 2026 and are indicative market ranges, not guaranteed salaries. In Pune specifically, fresher offers at services majors typically land lower in the band, while Salesforce-native consulting partners tend to pay somewhat higher for the same experience.",
    ],
    salaryBands: [
      {
        role: "Fresher / entry level",
        band: "₹3 – 6 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "1–3 years",
        band: "₹6 – 12 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "3–5 years",
        band: "₹10 – 20 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "5–8 years",
        band: "₹15 – 30 LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Senior / Lead",
        band: "₹20 – 35+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
      {
        role: "Architect / highly specialised",
        band: "₹25 – 45+ LPA",
        source: {
          label: "Archer Infotech Salesforce Career Guide 2026 — indicative India ranges",
          url: "/blog/salesforce-career-guide-pune-2026",
        },
      },
    ],
    hiringCompanies: [
      "Salesforce",
      "Accenture",
      "Deloitte",
      "TCS",
      "Infosys",
      "Wipro",
      "Cognizant",
      "Capgemini",
      "IBM",
      "Tech Mahindra",
      "LTIMindtree",
      "Mphasis",
      "Persistent Systems",
      "HCLTech",
      "Salesforce consulting and implementation partners",
    ],
    rolesAfterCourse: [
      "Sales Cloud Consultant",
      "Sales Operations Analyst",
      "Revenue Operations Analyst",
      "Salesforce Administrator (Sales Cloud focus)",
      "CRM Manager",
      "Salesforce Functional Consultant",
    ],
  },

  modesAndDuration: {
    duration: "2 months (8 weeks) for the weekday and online tracks; 10 weeks for the weekend track",
    classroom: {
      location:
        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",
      timing: [
        "Morning batch: Monday–Friday 10:30–12:00",
        "Evening batch: Monday–Friday 19:00–20:30",
        "Saturday lab session: 10:00–13:00 (org practice and Trailhead)",
      ],
    },
    online: {
      timing: [
        "Live sessions: Monday–Friday 20:00–21:30 IST",
        "Recordings in the LMS within 24 hours",
      ],
      tools: [
        "Google Meet for live sessions",
        "Salesforce Developer Edition org (free, and yours to keep)",
        "Trailhead and trailmixes (free)",
        "Data Loader (free)",
        "Slack batch channel",
      ],
    },
    weekend: {
      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],
      durationNote:
        "The weekend track runs 10 weeks rather than 8 to keep total contact hours the same.",
    },
    batchPolicy:
      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",
  },

  fees: {
    note: "Salesforce Sales Cloud sits in the mid band of our catalogue, reflecting a two-month duration. Salesforce examination fees are paid by you directly to Salesforce when you choose to sit, and are never bundled into or marked up in our fee. EMI is available — contact admissions for the current figure.",
    range: "₹25,000 – ₹38,000 (typical band) plus Salesforce examination fees, paid directly to Salesforce",
    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },
    paymentOptions: [
      "One-time payment (5% discount)",
      "EMI: 50% at enrolment + 50% at the midpoint",
      "EMI: three monthly instalments",
      "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee",
    ],
  },

  placementSupport: {
    paragraphs: [
      "Placement support is included in the fee with no separate charge, and starts in week seven. By graduation your resume is rewritten for Sales Cloud and sales operations job descriptions, your org walkthrough is rehearsed, and you have completed mock interviews on sales process and forecasting scenarios.",
      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",
    ],
    process: [
      "Week 7 — resume and LinkedIn rewritten for Sales Cloud and sales operations roles",
      "Week 8 — org walkthrough rehearsed and reviewed by the trainer",
      "Week 8 — first mock interview on sales process design scenarios",
      "Week 8 — second mock interview on forecasting and reporting scenarios",
      "Week 8 — certification-readiness check",
      "Post-course weeks 1–4 — introductions to partner companies",
      "Post-course weeks 5–24 — weekly placement-cell check-ins",
    ],
    partnerCompanies: [
      "Cognizant",
      "Accenture",
      "TCS",
      "Capgemini",
      "Persistent Systems (Salesforce practice)",
      "Wipro",
      "Infosys",
      "Coforge",
      "LTIMindtree",
      "100+ partner companies including the Salesforce-native partner network",
    ],
  },

  comparison: {
    intro:
      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",
    rows: [
      {
        feature: "Trainers named on the course page",
        archer: "Yes — with the org they work in",
        typical: "Generic 'certified expert trainers'",
      },
      {
        feature: "Practice environment",
        archer: "Your own Salesforce org from week one, kept after the course",
        typical: "Shared trainer demo org, or screenshots",
      },
      {
        feature: "Trailhead used alongside teaching",
        archer: "Yes — with a set sequence and trainer review of your work",
        typical: "Either ignored, or handed over instead of teaching",
      },
      {
        feature: "Certification fee",
        archer: "Paid by you directly to Salesforce, never bundled or marked up",
        typical: "Sometimes bundled at an unclear markup",
      },
      {
        feature: "Institute certificate versus Salesforce certification",
        archer: "Stated plainly — ours is a course certificate, only Salesforce can certify you",
        typical: "Blurred, deliberately",
      },
      {
        feature: "Downloadable syllabus",
        archer: "Yes — generated from this page, so the two cannot disagree",
        typical: "A one-page module list, or nothing",
      },
      {
        feature: "Project work",
        archer: "A build in your own org, documented and demonstrable at interview",
        typical: "Guided click-through with no artefact",
      },
      {
        feature: "Salary claims",
        archer: "Indicative ranges, sourced and labelled as indicative",
        typical: "A single large number with no source",
      },
      {
        feature: "Placement support duration",
        archer: "6 months after completion, no separate charge",
        typical: "1–3 months, or a vague 'until placed'",
      },
      {
        feature: "Batch size cap",
        archer: "18 weekday and online, 12 weekend",
        typical: "25–40 students",
      },
    ],
    closing:
      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",
  },

  versusAlternative: {
    heading: "Sales Cloud specialisation or the general Administrator course?",
    paragraphs: [
      "The Administrator course covers the whole platform to interview depth and is the broader qualification — it is the right choice if you do not yet know which part of Salesforce you want to work in, or if you want maximum optionality across roles.",
      "This course goes deeper into one cloud and assumes you already care about sales. If you come from sales, sales operations or business development, it is the shorter and more natural route, because you arrive already holding the sales-process judgement that takes an administrator years to acquire.",
      "Many people end up with both, in either order. The credential ladder reflects that: the Administrator certification is the foundation and Sales Cloud Consultant is the specialisation on top, and this course prepares for both.",
    ],
  },

  prerequisitesAndStart: {
    paragraphs: [
      "No programming and no IT background is required. Sales, sales operations or business development experience is genuinely valuable here and shortens the course considerably in practice, because you already understand what the platform is supposed to support. Complete beginners to both sales and Salesforce are better served by the Administrator course first, which covers more ground and does not assume the business context.",
    ],
    suggestedSteps: [
      "Read the Salesforce Career Guide 2026 on our blog to see where the sales path sits",
      "Create a free Developer Edition org and work through a lead-to-opportunity flow",
      "Check the upcoming batch dates and pick a mode",
      "Book a free counselling session if you are choosing between this and the Administrator course",
      "Enrol, and bring a laptop to session one",
    ],
  },

  faqs: [
    {
      question: "I work in sales but not in IT. Is this realistic for me?",
      answer:
        "Yes, and it is one of the more natural moves in the ecosystem. You already hold the half that takes administrators years to acquire — knowing why a stage exists, what a forecast category means to a sales director, and which fields a rep will quietly refuse to fill in. This course adds the platform to that, which is the shorter half. No programming is involved.",
    },
    {
      question: "Should I take this or the general Administrator course?",
      answer:
        "Administrator if you do not yet know which part of Salesforce you want, or want maximum optionality. This one if you come from sales and want depth in the cloud you already understand. The credentials stack in that order too — Administrator is the foundation and Sales Cloud Consultant sits on top — and many people take both.",
    },
    {
      question: "Does this cover CPQ?",
      answer:
        "At awareness level only — what CPQ solves, when an organisation genuinely needs it, and why it is a separate specialisation rather than a feature you switch on. Quoting, quote templates, discount approval and pricing governance in standard Sales Cloud are covered properly. If CPQ is specifically your target, treat it as a further step after this course.",
    },
    {
      question: "Why do so many Salesforce sales implementations fail after go-live?",
      answer:
        "Almost always adoption rather than configuration. Reps stop entering data when the system costs them more time than it returns, and once the pipeline stops reflecting reality every report built on it is fiction. Week seven covers this properly — measuring adoption honestly, reading the signals, and the intervention that usually works, which is removing a required field rather than scheduling more training.",
    },
    {
      question: "How much does a Sales Cloud specialist earn in Pune?",
      answer:
        "The indicative India-wide bands from our career guide are ₹3–6 LPA at entry and ₹6–12 LPA at one to three years, with sales operations and consulting roles moving higher. These are market ranges rather than promises. In this path specifically, business credibility with sales leadership moves the band as much as platform depth does.",
    },
    {
      question: "Will Einstein and AI replace this role?",
      answer:
        "No, but they change it. Einstein scoring, activity capture and forecasting are configured by someone who understands both the data and the sales process, and they fail visibly when that person does not exist — scoring built on a pipeline full of stale opportunities predicts nothing. The final module covers exactly this, including how to tell a sales director honestly that their data is not ready.",
    },
    {
      question: "Is the Salesforce certification exam fee included in the course fee?",
      answer:
        "No, and you should be wary of any institute that says it is. Salesforce exams are booked and paid directly with Salesforce at their published price, and the credential is issued in your name by Salesforce. Our fee covers training, your practice org, mock exams and preparation. Bundling the two obscures who is certifying you.",
    },
    {
      question: "Is an institute certificate the same as a Salesforce certification?",
      answer:
        "No. We issue a course completion certificate; Salesforce issues the certification, and only the second one carries weight in the market. Ask this plainly of any institute you are considering: is the certification issued by Salesforce, or by you? If the answer is unclear, that is your answer.",
    },
    {
      question: "Are weekend or online batches available?",
      answer:
        "Yes. The weekend track runs Saturday and Sunday mornings over a slightly longer calendar, and live online runs weekday evenings, both with the same content, the same trainer review of your work and the same placement support. Batch dates are shared through the contact form, on WhatsApp, or on +91 9850 678451.",
    },
    {
      question: "Is placement assistance included in the fee?",
      answer:
        "Yes, with no separate charge, and it runs for six months after the course ends. It covers resume and LinkedIn rewriting, rehearsing your project walkthrough, mock interviews, certification-readiness checks and introductions to partner companies. We do not guarantee placement — the institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock round.",
    },
  ],

  finalCta: {
    heading: "Ready to start Salesforce Sales Cloud training in Pune?",
    paragraph:
      "Two months from now you can have a complete sales process configured in your own org, an adoption rescue assessment in your portfolio, an org walkthrough you have rehearsed, and a clear run at the Administrator and Sales Cloud Consultant exams. If you already work in sales, you are starting with the harder half already done. Download the full syllabus above, visit the contact page, message us on WhatsApp, or call admissions on +91 9850 678451.",
  },
};
