#!/usr/bin/env python3
"""Emit the eight Salesforce career-path course pages.

The eight paths come from the site's own Salesforce Career Guide 2026
(/blog/salesforce-career-guide-pune-2026). Operational facts — batch timings,
fee structure, placement process, the comparison table — are genuinely
identical across all eight, so they are templated here rather than copied
eight times and left to drift. Everything that differs by path is authored
per course in COURSES below.

Salary bands mirror the career guide's table exactly, including its framing
that the figures are indicative rather than promised. Two pages disagreeing
about pay on the same site is worse than either number being imprecise.
"""
import json, textwrap

def q(s):
    """TypeScript double-quoted literal."""
    return json.dumps(s, ensure_ascii=False)

def arr(items, indent):
    pad = " " * indent
    return "\n".join(f"{pad}{q(i)}," for i in items)

SALARY_NOTE = (
    "Salary varies with experience, certification, development skill, cloud "
    "specialisation, company tier, communication and domain knowledge. The "
    "bands below mirror the India-oriented ranges in our Salesforce Career "
    "Guide 2026 and are indicative market ranges, not guaranteed salaries. In "
    "Pune specifically, fresher offers at services majors typically land lower "
    "in the band, while Salesforce-native consulting partners tend to pay "
    "somewhat higher for the same experience."
)

BANDS = [
    ("Fresher / entry level", "₹3 – 6 LPA"),
    ("1–3 years", "₹6 – 12 LPA"),
    ("3–5 years", "₹10 – 20 LPA"),
    ("5–8 years", "₹15 – 30 LPA"),
    ("Senior / Lead", "₹20 – 35+ LPA"),
    ("Architect / highly specialised", "₹25 – 45+ LPA"),
]

HIRERS = ["Salesforce", "Accenture", "Deloitte", "TCS", "Infosys", "Wipro",
          "Cognizant", "Capgemini", "IBM", "Tech Mahindra", "LTIMindtree",
          "Mphasis", "Persistent Systems", "HCLTech",
          "Salesforce consulting and implementation partners"]

PARTNERS = ["Cognizant", "Accenture", "TCS", "Capgemini",
            "Persistent Systems (Salesforce practice)", "Wipro", "Infosys",
            "Coforge", "LTIMindtree",
            "100+ partner companies including the Salesforce-native partner network"]

COMPARISON_ROWS = [
    ("Trainers named on the course page", "Yes — with the org they work in",
     "Generic 'certified expert trainers'"),
    ("Practice environment", "Your own Salesforce org from week one, kept after the course",
     "Shared trainer demo org, or screenshots"),
    ("Trailhead used alongside teaching", "Yes — with a set sequence and trainer review of your work",
     "Either ignored, or handed over instead of teaching"),
    ("Certification fee", "Paid by you directly to Salesforce, never bundled or marked up",
     "Sometimes bundled at an unclear markup"),
    ("Institute certificate versus Salesforce certification",
     "Stated plainly — ours is a course certificate, only Salesforce can certify you",
     "Blurred, deliberately"),
    ("Downloadable syllabus", "Yes — generated from this page, so the two cannot disagree",
     "A one-page module list, or nothing"),
    ("Project work", "A build in your own org, documented and demonstrable at interview",
     "Guided click-through with no artefact"),
    ("Salary claims", "Indicative ranges, sourced and labelled as indicative",
     "A single large number with no source"),
    ("Placement support duration", "6 months after completion, no separate charge",
     "1–3 months, or a vague 'until placed'"),
    ("Batch size cap", "18 weekday and online, 12 weekend", "25–40 students"),
]

def render(c):
    P = []
    A = P.append
    A('import type { CourseRichContent } from "./types";\n')
    A("/**")
    A(f" * {c['title']} — rich content overlay.")
    A(" *")
    A(textwrap.fill(c["doc"], 76, initial_indent=" * ", subsequent_indent=" * "))
    A(" *")
    A(" * Generated by scripts/build-salesforce-courses.py. Operational blocks are")
    A(" * shared across the eight Salesforce paths by design; edit the generator")
    A(" * rather than this file.")
    A(" */\n")
    A(f"export const {c['const']}: CourseRichContent = {{")
    A(f"  intro:\n    {q(c['intro'])},\n")

    A("  whyLearn: {")
    A(f"    heading: {q(c['why_heading'])},")
    A("    paragraphs: [")
    for p in c["why"]:
        A(f"      {q(p)},")
    A("    ],")
    A("    keyPoints: [")
    A(arr(c["key_points"], 6))
    A("    ],")
    A("  },\n")

    A("  whoIsThisFor: {")
    A("    forYou: [")
    A(arr(c["for_you"], 6))
    A("    ],")
    A("    notForYou: [")
    A(arr(c["not_for_you"], 6))
    A("    ],")
    A("  },\n")

    A("  curriculum: [")
    for m in c["curriculum"]:
        A("    {")
        A(f"      title: {q(m['t'])},")
        A(f"      weekRange: {q(m['w'])},")
        A(f"      description:\n        {q(m['d'])},")
        A("      topics: [")
        A(arr(m["topics"], 8))
        A("      ],")
        if m.get("highlight"):
            A("      highlight: true,")
        A("    },")
    A("  ],\n")

    A("  roadmapImage: {")
    A(f"    src: \"/images/courses/{c['diagram']}-v1.webp\",")
    A("    width: 1400,")
    A("    height: 900,")
    A(f"    alt: {q(c['diagram_alt'])},")
    A(f"    caption:\n      {q(c['diagram_caption'])},")
    A("  },\n")

    A("  syllabusDownload: {")
    A(f"    pdfUrl: \"/downloads/{c['slug']}-syllabus-v1.pdf\",")
    A(f"    title: {q(c['title'] + ' Syllabus — Complete Module List')},")
    A(f"    slug: \"{c['slug']}-syllabus\",")
    A(f"    blurb:\n      {q(c['pdf_blurb'])},")
    A("    asideBlocks: [")
    A("      {")
    A(f"        heading: {q('What is inside the PDF')},")
    A("        items: [")
    A(arr(c["pdf_inside"], 10))
    A("        ],")
    A("      },")
    A("      {")
    A(f"        heading: {q('Roles this syllabus prepares you for')},")
    A("        items: [")
    A(arr(c["pdf_roles"], 10))
    A("        ],")
    A("      },")
    A("    ],")
    A("  },\n")

    A("  projects: [")
    for pr in c["projects"]:
        A("    {")
        A(f"      title: {q(pr['t'])},")
        A(f"      description:\n        {q(pr['d'])},")
        A("      technologies: [")
        A(arr(pr["tech"], 8))
        A("      ],")
        A("    },")
    A("  ],\n")

    A(f"  trainersIntro:\n    {q(c['trainers'])},\n")

    A("  careerOutcomes: {")
    A("    paragraphs: [")
    for p in c["career"]:
        A(f"      {q(p)},")
    A(f"      {q(SALARY_NOTE)},")
    A("    ],")
    A("    salaryBands: [")
    for role, band in BANDS:
        A("      {")
        A(f"        role: {q(role)},")
        A(f"        band: {q(band)},")
        A("        source: {")
        A(f"          label: {q('Archer Infotech Salesforce Career Guide 2026 — indicative India ranges')},")
        A('          url: "/blog/salesforce-career-guide-pune-2026",')
        A("        },")
        A("      },")
    A("    ],")
    A("    hiringCompanies: [")
    A(arr(HIRERS, 6))
    A("    ],")
    A("    rolesAfterCourse: [")
    A(arr(c["roles_after"], 6))
    A("    ],")
    A("  },\n")

    A("  modesAndDuration: {")
    A(f"    duration: {q(c['duration_note'])},")
    A("    classroom: {")
    A('      location:\n        "Archer Infotech Kothrud campus (Flat No. 12, Divyadarshan Housing Society, Kothrud, Pune 411038)",')
    A("      timing: [")
    A(arr(["Morning batch: Monday–Friday 10:30–12:00",
           "Evening batch: Monday–Friday 19:00–20:30",
           "Saturday lab session: 10:00–13:00 (org practice and Trailhead)"], 8))
    A("      ],")
    A("    },")
    A("    online: {")
    A("      timing: [")
    A(arr(["Live sessions: Monday–Friday 20:00–21:30 IST",
           "Recordings in the LMS within 24 hours"], 8))
    A("      ],")
    A("      tools: [")
    A(arr(c["tools"], 8))
    A("      ],")
    A("    },")
    A("    weekend: {")
    A('      timing: ["Saturday + Sunday 10:00–13:00 (6 hrs/week)"],')
    A(f"      durationNote:\n        {q(c['weekend_note'])},")
    A("    },")
    A("    batchPolicy:")
    A('      "Batch sizes capped at 18 weekday and online, 12 weekend. New Salesforce batches start every 4–6 weeks — a slower cadence than the core development tracks, because each batch needs a trainer who is actively working on the platform.",')
    A("  },\n")

    A("  fees: {")
    A(f"    note: {q(c['fee_note'])},")
    A(f"    range: {q(c['fee_range'])},")
    A('    sourceCitation: { label: "Archer Infotech 2026 fee schedule", url: "/contact" },')
    A("    paymentOptions: [")
    A(arr(["One-time payment (5% discount)",
           "EMI: 50% at enrolment + 50% at the midpoint",
           "EMI: three monthly instalments",
           "Salesforce examination fees are paid by you directly to Salesforce and are never bundled into our fee"], 6))
    A("    ],")
    A("  },\n")

    A("  placementSupport: {")
    A("    paragraphs: [")
    A(f"      {q(c['placement'])},")
    A('      "We do not guarantee placement. Our institute-records rate is 90% across all tracks, measured on learners who complete training and clear at least one mock-interview round. The Salesforce tracks depend heavily on certification timing — graduates who postpone the official exam beyond six weeks of finishing place noticeably slower, which is why cert-readiness checks are built into the placement process rather than left to you.",')
    A("    ],")
    A("    process: [")
    A(arr(c["placement_steps"], 6))
    A("    ],")
    A("    partnerCompanies: [")
    A(arr(PARTNERS, 6))
    A("    ],")
    A("  },\n")

    A("  comparison: {")
    A("    intro:")
    A('      "Factual rows only — no logos and no opinions. Use it as a checklist against any Salesforce institute you are considering, including this one.",')
    A("    rows: [")
    for f, a, t in COMPARISON_ROWS:
        A("      {")
        A(f"        feature: {q(f)},")
        A(f"        archer: {q(a)},")
        A(f"        typical: {q(t)},")
        A("      },")
    A("    ],")
    A("    closing:")
    A('      "The single question worth asking anywhere: is the certification issued by Salesforce, or by the institute? Only the first one counts in the market.",')
    A("  },\n")

    A("  versusAlternative: {")
    A(f"    heading: {q(c['vs_heading'])},")
    A("    paragraphs: [")
    for p in c["vs"]:
        A(f"      {q(p)},")
    A("    ],")
    A("  },\n")

    A("  prerequisitesAndStart: {")
    A("    paragraphs: [")
    A(f"      {q(c['prereq'])},")
    A("    ],")
    A("    suggestedSteps: [")
    A(arr(c["steps"], 6))
    A("    ],")
    A("  },\n")

    A("  faqs: [")
    for question, answer in c["faqs"]:
        A("    {")
        A(f"      question: {q(question)},")
        A(f"      answer:\n        {q(answer)},")
        A("    },")
    A("  ],\n")

    A("  finalCta: {")
    A(f"    heading: {q(c['cta_heading'])},")
    A(f"    paragraph:\n      {q(c['cta'])},")
    A("  },")
    A("};")
    return "\n".join(P) + "\n"


if __name__ == "__main__":
    import importlib.util, sys, pathlib
    spec_path = sys.argv[1]
    spec = importlib.util.spec_from_file_location("sfdata", spec_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    for c in mod.COURSES:
        out = pathlib.Path(f"src/data/course-content/{c['slug']}-training-in-pune.ts")
        out.write_text(render(c), encoding="utf-8")
        print(f"  wrote {out}  ({len(c['curriculum'])} modules, {len(c['faqs'])} faqs)")
